### ISSUE TITLE
Map of FIT counts - enable filtering by country/NUTS

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#1]
https://test-eu-pollinator.pantheonsite.io/fit-counts-map

Enable zooming of the map/records grid to Countries/NUTS regions.  Following the approach on https://butterfly-monitoring.net/elastic/all-records

@andrewvanbreda

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Hi David,

Sorry for slow reply.
Before I look into this I better check about whether you are requiring the use of Elastic Search on this project.
If so there are some things to consider first

For Uk PoMS we don't, one of the primary reasons is that I don't think Elastic Search (as it is currently setup) returns samples that don't have occurrences.
I think for UKPoMS empty samples were considered important data.
How easy that would be to change I am not sure.
I am also uncertain about whether Elastic Search could be made to return the other reports (for instance I am unsure if the index has location_attributes in it).

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Also just noting I can't seem to assign people on this project, so if you are able to fix that in Github will be useful.

**Comment by DavidRoy** [comment]
I've hopefully given your access to assign people.  We do need to use ElasticSearch for performance reasons.  

Can you liaise with @johnvanbreda about extending the index to include samples with zero occurrences (important for several projects).  

The ES reports already work with country boundaries as I believe the location_ids (i.e. indexed locations) are included within ES?

**Comment by andrewvanbreda** [comment]
@davidroy
OK yes will do. Yes If using Elastic Search at least the boundary zooming is easier as already working with that.
I will check with John about getting these issues resolved.

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
John said this

"That's correct, the Elasticsearch index currently only holds occurrence data (along with the samples that contain the occurrences). So, an empty sample is not stored. "

I think John had already been given the go ahead to spend 1 or 2 days on this going by what he was saying, but he wants to know how urgent this is so he can fit this into his schedule (as I assume it wasn't high priority until now I guess).

The other snag is it is easier to make all the changes to Elastic Search at once, so I will need to let him know what other information I will need to report on (for instance the location_attributes are currently missing).

If you could let us know the priority of the Elastic Search changes,  we can work out how to best fit it in.

**Comment by DavidRoy** [comment]
I'll discuss priorities with john for the ElasticSearch updates and get back to you

**Comment by DavidRoy** [comment]
Closing as moving to ElasticSearch will be a separate issue
