### ISSUE TITLE
Restrict pan trap species data entry to role = 'Expert entomologist'

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#100]
We've agreed a change of approach for data entry of pan trap species data

Restrict data entry pages for user with role = 'Expert entomologist'
- [x] https://pollinator-monitoring.net/select-pan-trap-samples-add-insect-species-data
- [x] https://pollinator-monitoring.net/select-pan-trap-samples-add-insect-bycatch-data

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Done.
Note that no one currently has that role yet apart from my test user.
