### ISSUE TITLE
edit transect setup and results

### ISSUE THREAD

**Issue by iverkaik** [BiologicalRecordsCentre/SPRING#102]
Hi,

It seems that any collaborator can edit any transect setup when you go to the transect list:

![Screenshot 2023-01-05 at 11 32 13](https://user-images.githubusercontent.com/120505944/210759651-8f74b172-dcdf-4ce0-b836-172b474841da.png)

Probably better if this can be just edited by the "owner" and the regional coordinator? 
Regarding to this, some of the volunteers have been discouraged with the data entrance but it could be great if I can help them i.e. data uploading by the volunteer and/or by myself as a coordinator? would that be possible?

thank you,
iraima

**Comment by andrewvanbreda** [comment]
@DavidRoy 
David to comment on what to implement

**Comment by DavidRoy** [comment]
@andrewvanbreda restrict transect editing to owner and regional co-ordinator as suggested by Iraima

**Comment by andrewvanbreda** [comment]
Hi @iverkaik @DavidRoy 
System now does following

- Allows editing of own transects providing no walks have been entered
- Doesn't allow editing of own transect if there are walks, displays message to indicate this
- Regional coordinators/administrators can always edit, but are warned to proceed with caution if their are walks

Note that SPRING doesn't have the same setup with schemes as EBMS, so Regional Coordinators can edit any transect.
