### ISSUE TITLE
Cannot change bee identifications (i.e. links to hoverfly list)

### ISSUE THREAD

**Issue by JordyvdB97** [BiologicalRecordsCentre/SPRING#104]
Dear all, 

When I want to change a already uploaded bee identification than I can only choose from names from the "hoverfly species list" and not the bees (see the screenshots below). While entering a new bee works fine and I can select a bee species. 

So at the moment I cannot update / change already uploaded entries for the bees (hoverflies works). If you need any more information please let me know. 

Regards, 

Jordy van der Beek

![Screenshot from 2023-01-22 14-59-46](https://user-images.githubusercontent.com/58780238/213919757-d47971af-b905-48ca-8410-1cc5440b3a1a.png)

![Screenshot from 2023-01-22 15-00-31](https://user-images.githubusercontent.com/58780238/213919754-e791155d-e289-4403-8612-0275536604f1.png)

**Comment by andrewvanbreda** [comment]
Hi @JordyvdB97 
Sorry for slow response. 
David is away at the moment, and I hadn't realised I don't get Github email notifications for new issues unless David assigns it to me.
I will try this tomorrow and let you know.

**Comment by andrewvanbreda** [comment]
@JordyvdB97 
Thank you for this bug report.
What is happening is the bee grid is using the hoverfly species list when editing (which is clearly not the right thing to happen).
I cannot say how quickly I can fix this until I try.
If you have anything that needs changing urgently, let me know the exact details, and I will change it directly in the database interface we have.

**Comment by andrewvanbreda** [comment]
Hi @JordyvdB97
This is fixed.
It is working for me.
Close issue if happy, or give further feedback.
