### ISSUE TITLE
Entering butterflies from the pan traps

### ISSUE THREAD

**Issue by JordyvdB97** [BiologicalRecordsCentre/SPRING#105]
Hi all, 

As I already discussed with David during one of our monthly meeting would it be interesting to also be able to upload species entries for butterflies from the pan traps. Might be good to safe this information in the portal as well. 

This means to have next to hoverflies and bees also a section for butterflies in the "Insect SPECIES data from pan-trap samples" form. The species list can be the same as is used for entering the butterfly transects. 

Kind regards, 
Jordy van der Beek

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Let me know if this enhancement is to go ahead when you get back.

**Comment by DavidRoy** [comment]
@andrewvanbreda - yes, this is needed

**Comment by andrewvanbreda** [comment]
@DavidRoy @JordyvdB97 
Done and live.
Close if happy.
