### ISSUE TITLE
Wrapping specimen numbers in recording form

### ISSUE THREAD

**Issue by JordyvdB97** [BiologicalRecordsCentre/SPRING#106]
Hi all, 

Last question for today. Is it possible (and simple) to change the "Insect SPECIES data from pan-trap samples" form in such a way that the long specimen codes are wrapped. As all of our codes (I think for most institutes) are too long for the field. Which makes it harder to navigate through long lists of specimens and more easy to make mistakes. 

Either 
- the sample codes needed wrapping, 
- or the font size should be reduced, 
- or the field should automatically show the end-part of the specimen number, instead of the first part. 

Thanks a lot in advance!

Regards, 
Jordy van der Beek

![Screenshot from 2023-01-22 15-14-21](https://user-images.githubusercontent.com/58780238/213920687-73ce4ac9-de64-4849-b42a-14da1b82f81d.png)

![Screenshot from 2023-01-22 15-23-10](https://user-images.githubusercontent.com/58780238/213920822-c13b0abf-0045-42d4-9fe9-33f7df6af070.png)

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Are you able to pick this up? as it probably isn't good to use my support time on stylesheets that you are probably more familiar with.
Let me know if you can't

**Comment by BirenRathod** [comment]
@andrewvanbreda I just added "Grid Column Widths" . Also, I removed size of abundance from node.14.css. See if that works.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Thanks for looking into this.
I guess the abundance thing is a matter of personal preference as to what looks better. Personally I would leave as the full column width.
If you look at the following page though, we can see the Specimen Code is still a problem

https://pollinator-monitoring.net/species-data-entry?sample_id=21191187&implicit=f

![Screen Shot 2023-02-06 at 10 17 27](https://user-images.githubusercontent.com/2463614/216946779-df76261e-7ad7-4076-a4dd-082c761ab3c4.jpg)

**Comment by BirenRathod** [comment]
@andrewvanbreda I restored the size of abundance now. It was not doing anything. Also, reduced the size of the font for "Specimen code". It looks like in below screenshot.
![image](https://user-images.githubusercontent.com/5941255/216965923-7444a296-28a9-4111-9529-460631db0d93.png)

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Thanks for this. Looks like this meets the requirment.

Hi @JordyvdB97 
Please check you are happy with the result, and close the issue if ok.
