### ISSUE TITLE
How to handle new years in the Year filter on SPRING reports?

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#107]
@DavidRoy 
I have deployed a change for UKPoMS.
Would you like the same (or a variation of this) on SPRING?
https://github.com/BiologicalRecordsCentre/PoMS/issues/143

How to handle the Year drop-down on report pages like this
https://pollinator-monitoring.net/transect-walk-results

Currently the drop-down will add 2023 automatically, but it doesn't select the new year automatically (currently set to 2022).

2023 might be logical, but need to consider that if 2023 is default on reports, when the page first loads, the user won't see any data very early in January (which does have the advantage of not hammering the server every time the page loads)

**Comment by DavidRoy** [comment]
That works, thanks
