### ISSUE TITLE
Terms in termlists to be assigned to countries

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#11]
The ability to manage multi-value attributes on Warehouse1 went live the other week.

This means that:

1. The termlist of countries can be created. These will need to have the country codes included so then we can reliably link to locations in the future.

2. The terms in the termlists for the project can be assigned multiple countries name from that termlist by using a single multi-value lookup attribute.

Am I correct in thinking you will be handling the above tasks Jim? Let me know if not.

**Comment by andrewvanbreda** [comment]
A further thought on this, will species lists be limited in this same way, if so I think they will need a taxa_taxon_list attribute setup to do the same thing, and point to countries for each species.

**Comment by JimBacon** [comment]
I have created the 'FIT Count App Countries' temlist (id: 974) having terms

- United Kingdom (id: 18965)
- Cyprus (id: 18967)
- Argentina (id: 18969)
- Brazil (id: 18971)
- Chile (id: 18973)
Each term has the two-letter country code as a synonym.

I have created the 'FIT Count App Countries' term attribute (id: 8) and assigned it to the termlists:

- Habitats (PoMS) (id: 667)
- Target flower species (PoMS) (id:668)

Using the 'FIT Count App Countries' term attribute, I have tagged the terms in the 'Habitats (POMS)' and the 'Target flower species (PoMS)' termlists

I have created the  'FIT Count App Countries' taxon attribute (id: 190) and assigned it to the taxon list:

- Insect groups (PoMS) (id: 221)

Using the 'FIT Count App Countries' taxon attribute, I have tagged the taxa in the 'Insect groups(POMS)' taxon list.

**Comment by andrewvanbreda** [comment]
@JimBacon 
Thanks Jim, all sounds really good.
Just one thought really.
That is whether the termlist should be Owned By "Pollinator Monitoring Scheme" as that name is misleading (as it came about before EU PoMS existed). I think that is the UK PoMS website but not the EU one. (I did look at changing the name (to include UK in the title), but when I spoke to john there were a number of things to consider regarding that.)
So we may need to switch that owner to "Warehouse"? In practice it may not matter as there is a sharing agreement, but I am not sure.

**Comment by JimBacon** [comment]
I'd have attached it to the FIT Count website if I'd spotted that earlier as, in my head, this is all about the records coming from the mobile app.
If we can avoid it belonging to the Warehouse I'd see that as a good thing because it would be irrelevant clutter to 99% of users.

**Comment by andrewvanbreda** [comment]
@JimBacon @kazlauskis 
Note also (and not part of the original request as I always intended to create it) is I have created a sample attribute pointing at the country termlist

Sample attribute 1640

So now we know which country the samples were created and thereby we can work out what terms needs to be displayed by joining to the new multi-value attribute.
I will be adding that code to Indicia data entry forms and will let you know when done.
