### ISSUE TITLE
Regional co-ordinators need to be able to edit records

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#111]
As per title.

Also I think the My Transect Walk, My Fixed Square Results need investigating to make sure those also allow editing correctly.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
This situation has now been corrected.

One note.
For fixed square results I have only put edit icons on the samples grid, not the occurrences one.
This is deliberate, the problem is that some of those occurrences may have been added by people like expert entomolgists on the specialised species data screen, so they do not actually show on the standard data entry screen.
So clicking Edit would take the Regional Coordinator to the standard data entry screen and the occurrence they clicked edit for would not actually be present there to see.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Please check and close if happy

**Comment by DavidRoy** [comment]
Thanks Andy
