### ISSUE TITLE
SPRING: transect setup to allow number of sections to be editable

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#112]
The SPRING transect can now be either 5 or 10 sections.  Currently the transect setup defaults to 10 section:
https://pollinator-monitoring.net/transect-setup

This number needs to be editable.

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
How about this?
https://avb-section-eu-pollinator.pantheonsite.io/transect-setup

**Comment by DavidRoy** [comment]
That's great.  Please deploy to live

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Gone live.
Closing as you have already checked it is ok on clone of live.
