### ISSUE TITLE
Country to be applied to sample (also consider historical)

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#12]
When samples are submitted by EU PoMS related systems, they will need to indicate which country they apply to by using a sample attribute to point to a termlist_term ID in the countries termlist.

That termlist is being setup as part of issue #11

@kazlauskis You will need to make sure the app can do this. Am not quite sure we are in a position to have that working yet as the countries termlist exist.

I am also not sure what the plan is with historical data yet. We may have addressed that in previous emails, if so I will add details to this incident.
I suppose we will need to update the data to set the country, or alternatively finding a way to assume which country it is from.

**Comment by kazlauskis** [comment]
I hope I understood this correctly. This new sample attribute should represent the current user country and you want the FIT Count app to attach a this attribute to each survey that the app sends, is that correct? If so then what is the attribute ID?

**Comment by JimBacon** [comment]
From https://github.com/BiologicalRecordsCentre/SPRING/issues/11#issuecomment-979932909, sample attribute ID = 1640

**Comment by kazlauskis** [comment]
OK, we'll do it. I've moved the task to the app repository.

**Comment by kazlauskis** [comment]
If this is an app-only issue then it can be closed.

**Comment by andrewvanbreda** [comment]
Hi @kazlauskis 
It needs to be done on website too, I will look at this again once NPMS Drupal 9 move is done. Thanks for the app feedback in relation to this.

**Comment by andrewvanbreda** [comment]
Closing, covered by
https://github.com/BiologicalRecordsCentre/SPRING/issues/15
