### ISSUE TITLE
Create Regional Co-ordinator insect species download page

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#122]
Request from David.
Add similar functionality for SPRING that has been added here for UKPoMS.

https://github.com/BiologicalRecordsCentre/PoMS/issues/162

The main difference is the data is to be restricted and used by users with the Regional Co-ordinator role.

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy
How about something like this?

https://avb-downloa-brc-eu-spring-d10.pantheonsite.io/pan-trap-insect-species-entered-data

The UPoMS version of this page is for the user's own records. 
As you have requested limiting to the Regional Co-ordinator role, I have limited the report to the users' selected Coordination Country.

**Comment by DavidRoy** [comment]
That works, thanks

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy
This is now on live site.
