### ISSUE TITLE
Upload species data for Netherlands

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#124]
Data sent by email. Requirement is to upload Pan Trap occurrence data for samples already entered.
Similar process as for #117

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 

I have imported the files as per attached 
(essentially what you sent me split into 3 files + 1 extra re-import file for failed rows).

A couple of notes.
1. The bees file has a couple of rows where the sex is q/w, these were imported under the "mixed" category (can be changed if needed).
2. Three rows in the Hoverflies file didn't have their taxa_taxon_list ID filled in.
For one of these, the species "Anasimyia anausis" does not exist in the Syrphidae in Europe species list and that row has not been imported.
For the other two, I filled in the taxa_taxon_list ID and imported them in the Hoverflies_fixes file I have attached.

[Bees.csv](https://github.com/BiologicalRecordsCentre/SPRING/files/14180621/Bees.csv)
[Butterflies.csv](https://github.com/BiologicalRecordsCentre/SPRING/files/14180622/Butterflies.csv)
[Hoverflies_fixes.csv](https://github.com/BiologicalRecordsCentre/SPRING/files/14180623/Hoverflies_fixes.csv)
[Hoverflies.csv](https://github.com/BiologicalRecordsCentre/SPRING/files/14180624/Hoverflies.csv)

**Comment by DavidRoy** [comment]
@andrewvanbreda mostly ok but some final things to resolve. Here is the reply from my colleague at Naturalis.  Can you resolve these points?

A response to the points that Andrew made:
1. There were a couple of bees in the dataset where the sex was q/w, meaning queen or worker. This is what was noted in our original dataset. My intention was to change these to "f" for female, but I forgot. Perhaps f is better than mixed, but this is not a priority.
2. For the three rows of hoverflies without taxon ID, I could not find these in the list you sent me. Luckily Andrew did find the taxon IDs for Xylota segnis and Chalcosyrphus nemorum. The third one, Anasimyia anausis, has not been uploaded as it has no taxon ID. It is only one observation, so not a big issue, but could it be possible to create a taxon ID and upload this observation as well?

Finally, I have one question. I noticed that each specimen code is now uploaded twice. Once before DNA-barcoding, often only labelled "Bee (not identified)" for example. Then the second time after DNA-barcoding, this time with the species name. They have different occurrence IDs though. Are they supposed to be in the dataset twice? Or should the first upload without the species name be removed?

**Comment by DavidRoy** [comment]
On the last point, we need to mark occurences with 'Bee (not identified)' as deleted = t for these set of occurrernces.  These are duplicates due to my misunderstanding.

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 

1. Fixed. The mixed records changed to female on 2 occurrences.

2. I created the following taxon and imported the row using attached file
https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/629111
Note I only filled in very minimum detail on the taxon, edit it if you need more detail.

[Hoverflies_fixes_2.csv](https://github.com/BiologicalRecordsCentre/SPRING/files/14284326/Hoverflies_fixes_2.csv)


3.
I am not sure I can do anything about this without going through the entire dataset and doing manual deletions as I don't have access to the Warehouse DB to get the occurrence IDs. 
Having said that it might be tricky to do this automatically.
When we delete a "not identified" occurrence, we need to make sure there is an exact equivalent present that has been imported.
It would be easier for you to do the deletions if you are sure an equivalent accurate entry for each "not identified" entry has definitely been imported
I guess I could give it a go manually but the bees list looks long and tricky, or you could try internally to deal with it?

**Comment by DavidRoy** [comment]
No further action needed
