### ISSUE TITLE
Drupal sites require method of assigning user to country

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#13]
As per title

**Comment by andrewvanbreda** [comment]
@DavidRoy @JimBacon @kazlauskis 
Just working on getting the Drupal data entry forms working with the multi-lingual termlists, and the question about how to determine the user's country has cropped up.

Just to recap, when editing data, we determine what to show in termlists from the country held on the sample.

However, when adding new data we need a way to determine what is essentially a default country.

So my thinking is to have a country selected from a list held on the user's Drupal account, and if this isn't found then, we fall back on a default.
(although if the field is mandatory we would never fall back on a default).

So my plan is to have a drop-down of Countries as a Drupal field on their account.
This will then sync to a person attribute on the warehouse.
This attribute can then be used to limit the termlists in Add Mode on a data entry form.
The fallback default will probably be just be part of the form's configuration, or perhaps on the site's iForm settings, haven't go that far yet.

The implication of doing it this way is that the Country is set on a per site basis.
The attribute cannot be used to determine a user's country across all PoMS systems.
The exception to this would be if the user could only set their country in the one place across all systems, then other apps/sites could rely on that person attribute setting (as long as they never change it themselves)

Assuming we don't do it that latter way, the upshot is that on your own system, you are free to determine the user's default country any way you like. e.g. for the app you can do what you like to determine the country when adding new data, as long as that country is saved to the sample attribute.

Anyway, just let me know if anyone thinks there is a better/more practical way than what I have described above. Just mentioning this now before I do it, rather than after I do it

**Comment by kazlauskis** [comment]
It makes sense to store the user country in the Drupal account per website. We could then tweak the FIT Count app to set this field upon registration too.

**Comment by JimBacon** [comment]
I'm not sure of the benefit of syncing to a person attribute on the warehouse used to limit the termlists in Add Mode on a data entry form.

I'd be thinking of making Add and Edit mode as similar as possible and, in edit mode, you want to get the country from the sample attribute and not a person attribute. I can see you having a hidden input linked to the country sample attribute which you set to the value from the Drupal user profile when adding a record. 

I guess you would send the country value as a parameter when making the request for the terms to put in the different lists.

**Comment by DavidRoy** [comment]
I agree with Jim.  App users may change the country they submit observations from - therefore there is little merit in synchronising with a person attribute?

For the website input form, one option is to have a drop-down for country.  In reality, the website input form will be rarely used as FIT Counts are primarily app-based?

For editing, we will already have the country captured as a sample attribute?

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy @JimBacon @kazlauskis,

Yes, when editing data, the situation is clear, no problem there

In regards to adding data.

First thing, the person attribute I was originally talking about would only used by EU PoMS, the app can do what it likes for determining the country in add mode (however that may change given what Karolis was saying, but I will address that below).

Yes I totally agree about making the two modes as similar as possible, this makes sense. 
Actually, one of the reasons for my person_attribute suggestion is to make sure that they are similar, because when a user is adding data, we do a similar join to the country in the person_attribute instead of a sample_attribute. 

If we were to not do this, it would seem to me that the two modes become less similar, as one mode would join to an attribute in the Indicia database (the sample attribute) and the other would be trying to feed the Drupal country account field directly into the Postgres statements that load the attributes.

So I suppose it could be done that way, but am not sure of the advantage, so if there are advantages I am missing please let me know and we can go that route if it does turn out to be best. 

In regards to whether the EU PoMS site will be used in practice to make regular new data entries, I suppose in a sense the amount of usage doesn't matter, the fact the forms are present and available for use means the issue still needs addressing.
Unless you didn't want FIT Count entry forms for new data entry to be available at all on the EU PoMS site, and to restrict it to editing data only? then we wouldn't have the problem to solve and could just go with the sample attribute for loading termlists.
At the moment EU PoMS allows data entry, and FIT Count will be restricted to editing only.

In terms of the comment Karolis made. This is worth considering.
I think this could work if the country is set by the user when they register with the FIT Count site, and this is synced to a person attribute on the warehouse so that EU PoMS can also read that country when loading termlists.
This is actually very much preferable actually.

The thing that stopped me suggesting this is there isn't an order with which the user has to register with the sites, and this solution assumes the FIT Count site registration is carried out first.

What happens if a user registers with the EU PoMS Drupal site before FIT Count?
Perhaps EU PoMS could have a default country if this happens? 
If we could solve that, that would seem to me to be a very good way to go.

Someone could register with FIT Count, set their country, and this goes into a person attribute that could be used by any system at all that wishes to use it.

Andy

**Comment by JimBacon** [comment]
I was just trying to think of the simplest solution. I was aiming to avoid the extra person attribute and the synchronisation and the joining to the attribute by having the website just say, 'this is my country, give me the terms for it'. 

I think the down side is that, when editing, in order for it to work similarly and not join to the country attribute, you would have to make a request to find the country attribute of the sample first, and then feed that in to the form building.

I'll leave it to you to figure out which is easier to implement. It was just the way I thought to tackle it. 

Is it desirable for the selection of country in the app to affect the selection of the country in the EU POMS site (and vice versa)? The alternative is to keep the two independent and users are required to pick their country at registration with either.

**Comment by andrewvanbreda** [comment]
Hi @JimBacon
Yes I can see the reasoning for the suggestion, it does remove the attribute from the equation, so would appear to be simpler, def worth considering. 
I think really my argument was that the extra element that was being removed (the attribute) actually makes life more elegant. The country would always be an attribute, and therefore similar code can be used for both person and sample attribute country limiting.
To be honest, the use of the person attribute shouldn't be something to worry about, as my original thought was that it would be used by EU PoMS and only on the code I have written anyway.

Really I think my main concern was to do with the detection of the country.
Whether is should just be a Drupal account drop-down as originally suggested.
I didn't want to assume that was the case then find out that other people had intended something else.

(@DavidRoy we will need a decision from you on the following)
So this comes to the other point you mentioned, and I don't think this can be answered by me, but by David.
Do we want to have the country handled by each individual app/site......or do we shift it onto the FIT Count site and then allow all the systems to access that one setting.
From my own perspective, the one setting seems like a good idea, but I realise that might not match project requirements.

**Comment by andrewvanbreda** [comment]
Just to note.
I realised last night that actually the Drupal to Warehouse field syncing that I got working properly for NPMS (Drupal 7) might not have ever been ported to Drupal 8/9.
John contacted me a few months about this but I am not sure if he subsequently ported it to Drupal 8. I can see there is a commit "Easy login with Drupal 9 support" but looking at it I am not sure that syncing was ported.
@johnvanbreda Was this syncing ever ported?

So my current plan is
1. If it wasn't ported, and David doesn't want a universal country->I will use Jim's method without person attribute
2. If it was ported, and David doesn't want a universal country->I will use a person_attribute as I think that is simpler in that case.
3. If David does want a universal country, we will use a person_attribute shared by all sites/apps, and I will fix the syncing

**Comment by johnvanbreda** [comment]
@andrewvanbreda no I don't think so.

**Comment by andrewvanbreda** [comment]
This issue no longer needs to be open.
Only Regional Co-ordinators will have a country (issue #8).
For FIT Count data entry, in add mode, the country will be determined by a drop-down or similar field when the user first opens the page (#15).
