### ISSUE TITLE
Warehouse UI support for multi-value attributes

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#14]
The Warehouse UI must be extended to support multi-value attribute data editing so a multi-value attribute can be used to store the countries associated with particular terms.

**Comment by andrewvanbreda** [comment]
Work already completed. Created issue as a clear log of work done. Closing

**Comment by JimBacon** [comment]
Just used the new interface successfully. Great to have this feature at last.
An improvement would be to manage the appearance of synonyms in the list of options when it is a termlist attribute. 
In my case, I didn't want to see the synonyms.

**Comment by andrewvanbreda** [comment]
@JimBacon 
Hi Jim,
Yes I noticed that one.
I left it as it was already a more complex fix than I originally anticipated and needed to reach a point where I could release it otherwise I would go on forever.
So I decided to concentrate on making sure it was at least consistent and working across all attribute types.
