### ISSUE TITLE
Add option for marking locations as sensitive

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#16]
To enable users to hide locations from general reports

Suggest captured as a location attribute which then populates to samples and occurrences.

Consider sensitivity options of completely hiding locations or blurring the location

**Comment by andrewvanbreda** [comment]
@DavidRoy @JimBacon 
Note that the UK FIT Count data entry forms use a privacy_precision to achieve blurring.

Privacy precision is intended to be used if the reasoning for the blur is for the privacy of a location, but sensitivity precision is intended for use if the reasoning is for species sensitivity, so you may wish to consider which to use.
The results very similar but one is held at the occurrence level, and one is held at sample level and it is simply best to use the correct one for consistency.

NPMS had some code that sets a privacy precision of samples dynamically based on whether the location had been marked as private (which is a location attribute), so let me know if you think that digging that code out would be useful. It no longer does that, but the code would exist in some form on Github.

**Comment by DavidRoy** [comment]
An old issue
