### ISSUE TITLE
Import MVS location

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#20]
From files provided in emails from David dated

10/1/2022 13:34
10/1/2022 13:35
10/1/2022 13:37
10/1/2022 13:41
10/1/2022 13:42
10/1/2022 15:03

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy ,

I have had a look at the files you sent,

I think I have three queries at this stage, with the first being most important.

1. On UKPoMS, the squares actually use a square based spatial reference system such as OSGB, or Irish Grid.
The EU PoMS files you sent use X/Y coordinates, which is a point.
So I am wondering what to do about this.
Perhaps we could Zoom about this if easier to talk like that?
Firstly, on the data entry forms we zoom into the selected square, so without a geom this would be a point so that zoom won't work properly.
We could convert to a square based spatial reference system, but we would need a rule on how to approach that. For instance is the the X/Y point from one of th square corners, which one? (or the centre).
I suppose another option as there aren't millions of squares is to do the import using X/Y coordinates, but there manually draw squares as geometry on the map in the Warehouse,  although I guess that would not be accurate enough to be desirable.
I suppose another option is when the user selects the square, to not physically draw the square onto the map (as it is just a point), and prevent the map zooming in too far, but again likely an unwanted approach.

2. Are the X/Y coordinators decimal coordinates? I am not an expert on spatial reference systems (other than my day-to-day Indicia work with them), but I know there are degrees/minutes/seconds and perhaps other formats.

3. Do any of the other columns in the files need to be imported as attributes? (such as Institution, Län, Observatör), although these varies depending on the file.

Cheers

Andy

**Comment by DavidRoy** [comment]
@andrewvanbreda
1. we should work on the assumption that the locations are centroid points
2. this may vary by data source unfortunately but decimal co-ordinates for lat,long
3. can you combine the data sources and I'll review

**Comment by andrewvanbreda** [comment]
[Combined locations (UTF-8 with bom) .csv](https://github.com/BiologicalRecordsCentre/SPRING/files/7854562/Combined.locations.UTF-8.with.bom.csv)

Hi @DavidRoy ,

Find attached the combined locations, with the following notes

1. File is in csv "UTF-8 with bom" format.
In my previous experience of multi-lingual projects, this is the file format Indicia can import where the language specific characters will not glitch.

2. The folders you supplied have some image files, and a KMZ file. I have assumed these did not contain any useful information to import, and everything was in the spreadsheets.

3. There are a few rows without much information (e.g. mostly saying N/A). I have included these rows in the combined file (even if they are ultimately removed), as they may have been placeholders for other information to be inserted.

4. I have included almost all the columns from the files, and if it is totally obvious that two columns are equivalent but named differently, I have combined them.

5. The only data I have not included is in one file there was a column which was just 1,2,3,4 etc rows numbers. I also removed the numbers from the location names in the Sample sites for MVS 2022 NL.xlsx file

6. The file which had 2 names for the location name (Romanian/Hungarian) has had the location names combined with a slash separating them.

7. I have kept the original X/Y/Lat/Long columns from the files as they were. I have not combined these, so there are 4 coordinate columns.
In theory these can be combined.
However...... 
Looking in the SPRING_sites_AtlanticMediterranean file, I think the X/Y are wrong way round, I believe Y should be latitude.
Can you confirm that conclusion?
There is one file Sites_David_Roy where I didn't understand the meaning of the X/Y Coordinates, so if you could let me know about that at some point before import.
For these reasons, I have left the spatial reference coordinates in the combined file to be the same as the original data even if I suspect it could be combined or corrected.

**Comment by DavidRoy** [comment]
@andrewvanbreda here is an updated file for loading - only sites where we have the co-ordinates (lat, long in WSG84)
Can you load these in?
[SPRING MVS sites for loading 24-01-2022.txt](https://github.com/BiologicalRecordsCentre/SPRING/files/7924248/SPRING.MVS.sites.for.loading.24-01-2022.txt)

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy,

I have obviously only had time to quickly look at the file, but this does look like the kind of thing that can be uploaded.
I suppose the only thing is we need to choose a method of displaying  these as squares to the user (whether we are going to try and display the use some geom for the square, or whether they will just remain a point on the screen and we stop the map zooming in too close to the point)

**Comment by DavidRoy** [comment]
@andrewvanbreda.  Points are fine.  The main purpose is to allow partners to zoom into the right place and attach sub-locations (pan trap locations and transects routes) to these 'master sites'

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy ,

I have made some minor alterations to the file to allow it to be imported (change the file type to allow special character import, put spatial reference into one column).

Before I do the import, I have some points I think will need answering.

1. I assume the SPRING Code should go into the location code?

2. Do you want the Spring region imported?

If so, do you have a full list of the regions so I can create them? and should they be parent locations or a link through an attribute to a termlist?

3. I notice there is also a country code.
Does this link need importing?

If so, I have similar questions to point 2
Would that be a link to a location? or would it be link to the termlist of countries that Jim created?
The current problem with the latter is that list doesn't have many entries in it at the moment.

http://warehouse1.indicia.org.uk/index.php/termlist/edit/974



If you would like my opinion on the above questions I would say the following

1. Yes the location code

2. I don't know the answer to this one.

3. Don't import with link to the countries, as the spatial index builder would create links to required locations (and having the link to the termlist would add redundant information).

**Comment by DavidRoy** [comment]
Thanks. My responses to the three questions.
1. yes
2. I can't see an immediate need for this so let's opt for simplicity and exclude
3. I would like an attribute for this but does not need to link to the termlist

**Comment by andrewvanbreda** [comment]
@DavidRoy 
I did a an import onto test warehouse which worked apart from it seems to me that the spatial references are wrong on half the file, can you confirm that the latitudes/longitudes are the wrong way round from the row "Réserve naturelle du Massif du Saint-Barthélémy" downwards? I can correct that for the live import if you confirm my thought. 
Thanks

**Comment by DavidRoy** [comment]
@andrewvanbreda if the locations don't match the country then that sounds plausible.  Please go ahead and re-import after switching x,y as you suggest.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Import is done. Using the attached file.

If you want to check this yourself (up to you), you can search for locations with the "SPRING MVS location" location type in the Warehouse UI.

[MVS sites (adjusted spatial refs) (utf-8 with bom).csv](https://github.com/BiologicalRecordsCentre/SPRING/files/7957983/MVS.sites.adjusted.spatial.refs.utf-8.with.bom.csv)

**Comment by DavidRoy** [comment]
Thanks @andrewvanbreda 
Can you create a simple map page on the website for me to review?  Feel free to raise a separate issue for this

**Comment by andrewvanbreda** [comment]
Closing.
Feedback on data entry forms entered in issue #21
