### ISSUE TITLE
Questions/thoughts to consider before go live

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#21]
Thread to hold information, discussion before go live of the main SPRING site.

@DavidRoy It would be useful to get an idea of what would be the minimum elements required for go live, so I can indicate where we are with these, and see if there are any blockers.

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 

I think this issue is a suitable place to put the feedback regarding the data entry pages.

We have not spoken about this project in person for a while, so we might need to zoom at some point about getting this live.

For the data entry side of things:
From my point of view there are 3 data entry pages I am in charge of doing on the SPRING website itself.

1. 
Enter FIT Counts
My understanding this is effectively a clone of UK PoMS.

I already cloned this here
https://test-eu-pollinator.pantheonsite.io/enter-fit-count

However there will be problems with the instructions as they are UKPoMS instructions, I am not normally responsible for the text instructions given to users.

Note this pages will currently have language issues in the termlists/species list. 
I coded the language selection for termlists but was then waiting an answer from Jim before putting that live, I have not checked recently whether that was answered because been busy with other things. I will do that.

Aside from that, this page should function.

2. "Enter results for you fixed square survey"
https://test-eu-pollinator.pantheonsite.io/add-1km-samples

In a similar way, this is currently a clone of UKPoMS pan-traps, so all the instructions will be wrong.

I have changed the 1km square field field to point at those new locations we have imported. 
You will see the map problem I mentioned would happen where it zooms so I need to change the code driving that.

Otherwise this page should function.

3. "Enter results from your fixed square malaise trap"
I don't think I have a specification for this page at all, so it is only a placeholder.
https://test-eu-pollinator.pantheonsite.io/enter-malaise-records

I can't work on this 3rd page as have no idea what to put on it currently.

I will continue to work on these pages, but I don't think I can reach a finish point without further input as noted above.

Andy

**Comment by andrewvanbreda** [comment]
@DavidRoy 
It was much easier than I thought to prevent the map zooming in too far because the location_autocomplete control respects the map panel maxZoom option.
You could check if this is the kind of page you want (you will have to ignore that the text on the page is from UKPoMS).

https://test-eu-pollinator.pantheonsite.io/add-1km-samples

**Comment by DavidRoy** [comment]
@andrewvanbreda looks generally good.  

for your no. 1 FIT counts
Shall I edit the page explanation text directly?

For your no.2 and add samples page
A few initial suggestions:
1. rename page to 'add-pan-trap-samples'
2. have an option to choose country first, to then restrict site locations to those within that country
3. Pant trap station needs to increase to 1 to 10.  SPRING has more trap sets
4. For the plant species - is this a UKSI list?  Is it restricted to a subset of species?  We'll need to swap this for an EU list

For your no.3
The 'malaise' trap entry page is low priority and not required for first live launch

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy ,

In answer to your questions.

In terms of editing the text. 
Yes direct edits to the page text are easier, but there are problems with both of us making alterations at the same time. There is also a risk that mistakes from either one of us could interfere with what other is doing.

So what I have done is make sure that those 2 data entry pages on DEV are updated to be identical to TEST. 
So if you make your changes on DEV, I will do mine on TEST, then when you are done I will merge your text onto the test site

https://dev-eu-pollinator.pantheonsite.io/enter-fit-count
https://dev-eu-pollinator.pantheonsite.io/add-pan-trap-samples

1. I have renamed the URL as requested. I wasn't actually sure if you wanted the main page title to change as well.
Perhaps you can just adjust that as required when you make your text changes.
(note the previous URL was just the same one that was used by UKPoMS)

2. Yes we can do this, but I will need to make some adjustments to the imported locations, their country is currently just a text attribute holding the code.
I will need to think of best way to do this.
Will the list of squares (and countries to select first) be expanding in the future?

3. Yes we can just use a new attribute for this.
Currently the page uses the same attributes as UKPoMS.
This now leaves a difficult question.

We need to decide if all the other attributes should actually be shared with UK PoMS.
Are the attributes on the pages likely to change at all in the future and diverge from UKPoMS?

4. On the pan trap square page, the species list is currently UK Master List filtered by the "flowering plant" taxon group.
This can be adjusted if you can point me to the extact species list you want to use, and any filtering to limit the items shown.

**Comment by DavidRoy** [comment]
@andrewvanbreda Thanks. I'll edit on the dev site.
3. We should align with the UKPoMS attributes as far as possible.  There should be relatively few cases where the EUPoMS deviates

4. Ok, I'll work with Jim to have an EU equivalent.  We can keep the UKSI version for the time being

**Comment by andrewvanbreda** [comment]
3. Fixed, Pan Traps on SPRING is now a separate 1-10 list

**Comment by DavidRoy** [comment]
For 2, Jim has implemented the country selection option on https://butterfly-monitoring.net/moth-trap-details

**Comment by andrewvanbreda** [comment]
@DavidRoy OK thanks for tip.
Will have a look at how it works there and use the same method on SPRING

**Comment by andrewvanbreda** [comment]
@DavidRoy @JimBacon 
Am I correct in thinking the butterfly page is different as the location control is just free text? 
It doesn't seem to be limited to a specific set of locations (and is therefore different in nature). So we need a new extension for SPRING that combines a square drop-down with country filtering alongside the butterfly code which can detect if the spacial reference is outside the country.
Thanks for clarification.

**Comment by andrewvanbreda** [comment]
Hi @JimBacon 
On the butterfly site do you know where the code that displays this message is?
"The new location is outside the boundary of the previously selected parent"

I wanted to use this so the pan-trap spatial reference is forced inside the square.
Is it in a node.x.js file? As don't have this project on my Pantheon Dashboard, would you be able to send it to me please so I can reuse it.
Cheers.

**Comment by andrewvanbreda** [comment]
@DavidRoy @JimBacon 
Actually I think there is something I don't quite understand about how this is going to work having thought about it again.
For SPRING, the country is to be selected first as a filter for the squares to show the user.
The square is then selected by the user, but this is just a WGS84 point.

The user then selects a pan-trap number.

Now on UKPoms the squares are OSGB, so are an actually square, and these are not actual linked to the sample spatial reference.
The user is free to enter whatever they like there.

This makes sense, as the pantrap can be a more precise location inside the square.

But with SPRING all those squares are in WGS84 points.

David: Should the sample spatial reference just match the square point on SPRING?
If so I am not sure there is any of Jim's butterfly code to be reused here.

Alternatively, If the sample is to have its own spatial reference that is going to be different to the square point, then I can't detect it is inside the square anyway, and Jim's code would be of minimal use here (unless you wanted to enforce that it was inside the country).

**Comment by JimBacon** [comment]
> On the butterfly site do you know where the code that displays this message is?
> "The new location is outside the boundary of the previously selected parent"

iform/client_helpers/prebuilt_forms/js/dynamic_location.js

**Comment by andrewvanbreda** [comment]
@JimBacon 
Thanks Jim. That is what I thought when I first started working on this the other day, but when I checked again this morning I couldn't see it.
I now see what I have done, the text wasn't being found in my searches because it is in the language file and is split over several lines.
Cheers for the tip

**Comment by DavidRoy** [comment]
Closing this issue as it drifted from the original title
