### ISSUE TITLE
Drive downloads and grids separately for efficiency gains

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#22]
Most pages currently drive their grid and CSV download from the same report. 
This will move to ElasticSearch soon, but I can see some quick gains to be had before then on some pages by changing this straight away.
In particular, I think Regional Coordinator Download suffers inefficiencies because of this (where it is reporting on lots of people's data, and the grid and download are very different).
@BirenRathod: could you pull these onto live whenever you get chance please. Not urgent (also safe as these reports are not in use until I configure them).

	reports/projects/PoMS/regional_coodinator_grid_2.xml
	reports/projects/PoMS/regional_coodinator_grid_2_download.xml

Thanks :)

**Comment by BirenRathod** [comment]
@andrewvanbreda Those reports have gone on live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod Great thanks Biren

**Comment by andrewvanbreda** [comment]
Closing as now covered by 
https://github.com/BiologicalRecordsCentre/SPRING/issues/96
This issue has a natural requirement to have different functionality in the download grid.
