### ISSUE TITLE
FIT Count website permissions not correct?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#23]
@BirenRathod @andrewvanbreda 
i don't think the permissions are right on the FIT Count website.

1. login as admin
Blank report maps for the regional results page: https://fitcount.ceh.ac.uk/regional-results

2. masquarade as user setup with role = regional co-ordinator (https://fitcount.ceh.ac.uk/user/67)
The regional/my results pages are not showing

Does this relate to the wider issues with Drupal permissions that has been fixed on other sites?  Maybe the fitcount website didn't get checked?

**Comment by BirenRathod** [comment]
@DavidRoy Permission has been re-instated now.

**Comment by DavidRoy** [comment]
Thanks
