### ISSUE TITLE
Refine user roles

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#25]
Current roles on https://test-eu-pollinator.pantheonsite.io/admin/people are:
UKCEH STAFF
CONSULTANT ENTOMOLGIST
1KM SQUARE VOLUNTEER

Rename to:
UKCEH STAFF -> SPRING STAFF
CONSULTANT ENTOMOLGIST - EXPERT ENTOMOLGIST
1KM SQUARE VOLUNTEER - MVS SITE VOLUNTEER

Role to add:
REGIONAL CO-ORDINATOR

**Comment by andrewvanbreda** [comment]
Done, close when happy (I realise there are other issues that will over the new role)

**Comment by DavidRoy** [comment]
Thanks
