### ISSUE TITLE
Restrict MVS site editing to regional co-ordinators

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#26]
linked to #25 

Restrict access to: https://test-eu-pollinator.pantheonsite.io/list-squares
for users with role = regional co-ordinator

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Done, However, what about the actual square editing?
Should they be able to edit the squares? (currently they can't because the system will tell them they don't own the square).

**Comment by DavidRoy** [comment]
@andrewvanbreda yes, this role should allow editing of the site locations

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Done. Close when happy.
Note: I also fixed a problem where editing a square would cause it to vanish from the list on the site.
The system was switching the type to a UKPoMS square upon save.
Have corrected the incorrect configuration (and tested it) and also reinstated the correct location type on the squares so they are now present again

**Comment by DavidRoy** [comment]
Thanks.  This works from my testing.  There are some changes needed to the map functionality but I'll raise that separately
