### ISSUE TITLE
MVS sites - map of progress

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#27]
Changes required to existing page
https://test-eu-pollinator.pantheonsite.io/square-volunteer-pantrap-statuses

- [x]  page title changed to = SPRING Site summary
- [x] make page public
- [x] change url to .../mvs-site-summary

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Have done this, although have noticed another issue which is preventing this working correctly.

@BirenRathod 
You know that problem about a month ago where we were losing all the permissions on Drupal sites
https://dev-eu-pollinator.pantheonsite.io/
&
https://test-eu-pollinator.pantheonsite.io/
Are you still about to reverse those losses?, it looks like all the basic permissions are missing on the above sites.
Most of the "Indicia Forms" permissions on the Permissions page seem to be admin only.
Thanks for any info or assistance.

**Comment by BirenRathod** [comment]
@andrewvanbreda Have you got anything on dev (https://dev-eu-pollinator.pantheonsite.io/) site which might lose if I clone test site on it?

**Comment by andrewvanbreda** [comment]
@BirenRathod 
I haven't as I use test as my main development site, then I copy the changes to dev.

I did speak to Jim and he has been moved off project, so I would imagine he doesn't have anything on dev
@JimBacon Are you able to just confirm you don't have anything on dev before it is overwritten.

**Comment by BirenRathod** [comment]
@andrewvanbreda I have re-instated most permissions. there is not much to do but let me know if anything missing. It is on dev website. Once you satisfied, I replicate that onto live.

**Comment by JimBacon** [comment]
> @JimBacon Are you able to just confirm you don't have anything on dev before it is overwritten.

I have nothing on dev, thanks.

**Comment by BirenRathod** [comment]
Thanks, @JimBacon. I restored backup from test on dev site. So dev and test site should be same.

@andrewvanbreda As I mentioned above checked all permission is ok on dev site and let me know, so I can implement that too on test site.

**Comment by andrewvanbreda** [comment]
@BirenRathod @DavidRoy 
Thanks Biren.

Without me examining every single permission against the PoMS permissions spreadsheets, it certainly looks by eye like those permissions are the right kind of thing now. So am happy with that.

@DavidRoy 
I notice the Regional Co-ordinator has some extra permissions, I assume you added those?

Both: David made some changes to the 1km squares page this morning which I have copied across to Dev else they would be overwritten.
@DavidRoy : Are you able to confirm those are the only alterations you have made to the site recently (since the last backup of Test, whenever that was)

Biren: if there is a problem when DEV is moved onto test, I assume there will still be a backup of test that could be restored if necessary.

**Comment by DavidRoy** [comment]
@andrewvanbreda I've lost track of progress on this.  The issue remains, in terms of a map of progress on the live site

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Would you be able to pull this report whenever you get a chance please. Thanks

/reports/projects/PoMS/eu_pollinator_squares_summary_mappable.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda  that report gone live now.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Thanks Biren

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
This is now on the site. 
There is one big question though, who should be able to see the page?
To be safe, I currently set this to anyone who can access the square management page (same as UK PoMS does for equivalent page).
I noticed you said "make page public" above, so I suspect that it should be any registered user instead?
Can you confirm?

I made the adjustments you suggested, by also some other adjustments.

1.  Slightly more zoomed in, better centred map.
(Same change made to List Sites page).

2. I removed a few of the comments at the top of the page which were left over from UKPoMS, and were not accurate to EU PoMS.
However I left this comment...
"Please note that most of the land within these squares is privately owned, and this map does not imply that any public access is available."

3. I changed the available layers to be OpenStreetMap and Google Hybrid, to match the List Sites page map.

4. The report running on the page has been changed slightly, as before it was more appropriate to UK PoMS.
I have added a sort order (it had no official sort order before), It is now sorted by location code, let me know if you prefer something else.
Also I changed the colours on the map to be based on if the square has been surveyed, previously it was based on if the square is allocated to a person (using a attribute flag on the square, I don't think that attribute has been used by EU PoMS).

**Comment by DavidRoy** [comment]
Thanks.  Have edited the page text.
