### ISSUE TITLE
FIT Count Website - All Results page (and discussion details)

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#28]
FIT Count website to have
"an ‘all results’ page to the FIT Count website so that everyone can view (but not download) what is being submitted.  This would be a clone of the standard results page but without a geographic restriction and without the download link.  The page would ideally have a country boundary selector, but does not need the survey type selector."

Edited details of the discussion that lead to this requirement are below

**Comment by andrewvanbreda** [comment]
**From Claire** 
You’ll be aware that we have several countries now wanting to adopt the FIT Count app, including across the EU and S America.
 
The basic functionality that we can offer them aside from the app itself is through the current FIT Count website which will host a page for each country (to provide links to their own project websites etc) and allow users to view and download their own counts on a map via this link:
https://fitcount.ceh.ac.uk/my-results
 
Our Brazilian colleagues have now asked if they can use the functionality provided within the main PoMS site to view country-wide maps of all counts coming in, and also the target flower visualisation plots.
 
Is the code for both the maps and the target flower plots available on GitHub? Could it be shared so that any country co-ordinator could run their own counts through it (following download) to display on their own (local) website?
 
Alternatively, would it be feasible to at least remove the ‘UK country boundary’ from the current map on the PoMS website (but not from the target flower charts) so that someone in Brazil could zoom out and see how many counts are coming in there? It would be quite exciting to have an international view as things expand!
https://ukpoms.org.uk/fit-counts-map 
I’m very wary of promising too much and don’t want to get locked into supporting the S American teams too heavily after our project budget ends next month.
 
David, I’m not sure where you are on this element with the EU partners so apologies if that discussion is already ongoing."


**Response from David**
A few things from my perspective.
1. The Brazilian co-ordinator can view (with map) /download the FITCount data via the FIT Count website.  
https://fitcount.ceh.ac.uk/regional-results.  
It does not include the summary at the top of ‘x counts submitted…’

2. Andy - I think it makes sense to have an ‘all results’ page to the FIT Count website so that everyone can view (but not download) what is being submitted.  This would be a clone of the standard results page but without a geographic restriction and without the download link.  The page would ideally have a country boundary selector, but does not need the survey type selector.  I’ll raise an issue for this.

3. The code-base for Rich’s charting library is at: https://biologicalrecordscentre.github.io/brc-charts/ with the pie chart examples at https://biologicalrecordscentre.github.io/brc-charts/docs/example-1.html


**Response from Claire**
Thanks so much David, I had forgotten that the Regional results page was already set up, for some reason I don’t think it appeared on my account yesterday? But I can access via that link and see it now.

**Comment by DavidRoy** [comment]
@andrewvanbreda do you have an eta for this?

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Sorry have been sidetracked with NPMS Drupal 9 upgrade.
There is an unknown here, and that is whether performance will be ok. I will try to get the report done in next few days.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Have coded this now. Have made it such that by using a different configuration ,these can also replace the existing regional co-ordinator reports as they are similar
@BirenRathod : Would you be able to pull these onto the test and live warehouse whenever you get a chance please. Cheers
reports/projects/PoMS/fit_count_results_grid.xml
reports/projects/PoMS/fit_count_results_map.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda I have pulled reports on both servers now.

**Comment by andrewvanbreda** [comment]
@BirenRathod Thanks Biren

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Sorry Biren, I only just got around to checking this. I started setting up the page on the site and realised I made a mistake, I forgot to also commit the supporting sub-report,
Could you also please pull this report onto both warehouse splease whenever you get a chance. Cheers
projects/PoMS/get_countries_for_population_call.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda That is fine. That report gone live now.

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy ,

I have setup a preliminary page for you to check (not in menu yet until its ready, so go directly to the URL).

https://fitcount.ceh.ac.uk/all-results

(Note: there is a bug I noticed where if you don't select a country, there is an error.
I will address this depending on your other answers.
For now please make sure you select a country)

Please check it and let me know your thoughts (with my following notes as guidance)

Some questions

1. 
Do you want it to default to a particular country?

2. 
Do you want to allow a selection of no country (so all data)?, I could remove the '<please> select>' option if you don't want that.
If so, we would need a default country as per point 1.
I guess this would be really slow though (although I can't check that as the no-country selection doesn't currently work)

3. 
Which users do you want to be able to see the results page?

4. 
Presumably you want the year to default to 2022?, but the other reports currently default to 2021, do you want these other reports changed to 2022? (My Results, Regional Results).

5. Do you want the report to run as soon as the page opens, or do you want the user to make their selections first?

Ideally we would move a lot of this reporting to Elastic, but my discussions with John about that have been problematic.

Andy

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren, I fixed the problem with the country selection.
If it is easy to do this could you pull these reports on both warehouses please. Cheers,
Alternatively you could just pull on live if that makes things simpler.
If a pain, just leave it and I will get back to you once David has checked them.
reports/projects/PoMS/fit_count_results_grid.xml
reports/projects/PoMS/fit_count_results_map.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda I have pulled those reports on live warehouse but on testwarehouse, it didn't. Seems like you haven't committed those into develop branch.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Ok thanks, that is fine.
I don't think indicia-reports has a Develop branch
