### ISSUE TITLE
Add Germany sites to MVS site list

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#29]
links to #24 #20 

new sites emailed...

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy,

I looked at the file. I have these questions.

1. This file does not have a location code.
Should I concoct one from applying a country code to the "No" number column using the same format as the other sites.

2. Do the habitat, height columns need to be importing? we don't have that info imported for the other sites.
Also if the we don't use my idea for point 1, then will the "No" column also need importing?

3. Should the comment field be imported into the location comment? (there only seems to be a little bit of information in this column and the other locations don't have anything in the comment).

**Comment by DavidRoy** [comment]
Thanks @andrewvanbreda 
1. yes, similar to other countries please
2. no, only the attributes we already have
3. no

**Comment by andrewvanbreda** [comment]
@DavidRoy @johnvanbreda
I was able to do this on test warehouse, but live is giving following error as soon as I enter the location importer.

Locations Import
Fatal error: Cannot redeclare hostsite_get_user_field() (previously declared in D:\websites\warehouse\application\views\importer.php:30) in D:\websites\warehouse\application\helpers\warehouse.php on line 30

**Comment by JimBacon** [comment]
That sounds familiar... I might have fixed it in dev.

**Comment by JimBacon** [comment]
https://github.com/Indicia-Team/warehouse/commit/3fb43611ee99545a8d7e683bab1b5ff01b68340d

It probably went in dev as I was a little uncertain it would work in all situations.

**Comment by andrewvanbreda** [comment]
@JimBacon 
Thanks for the info.
I assume I just need to wait for this to make its way onto live then.

**Comment by johnvanbreda** [comment]
@andrewvanbreda yes, I'll be rolling out a new release imminently.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
I noticed the Warehouse has been fixed, so I have done the import now.
Note there are two locations with the name "Diersfordter Wald (Kreis Wesel)", and two with the name "Pliesterberg (Kreis Wesel)".
These can be adjusted in the warehouse if you want to make the names unique.

Close the issue if you are happy the way things are.
