### ISSUE TITLE
Moth data entry -  improve description of trap details

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#3]
e.g.
1. Trap type
2. Lamp type

tbc

**Comment by JimBacon** [comment]
Further detail provided by Chris van Swaay.

Trap types are 

- LED trap
- Robinson trap
- Funnel trap
- Other (+ text box)

Lamp types are:

- 395-405 SMD 2835 LED-strip (50cm)
- 395-405 SMD 5050 LED-strip (50cm)
- 2 x 2 watt LED
- 6 watt actinic
- 8 watt actinic
- 2 x 8 watt actinic
- 18 watt blacklight
- 20 watt Sylvana UV-A
- 2 x 20 watt Sylvana UV-A
- 125 watt HPL
- 2 x 125 watt HPL
- 160 watt ML
- 160 Watt Omnilux blacklight
- 250 watt ML
- 125 HPL en 250 ML
- 400 watt HPL
- Other (+box to enter type)

We should make it very clear that we always want to use traps which are on from dawn till dusk, so the whole night is captured. This means that standing with a sheet and lamp until 2 AM is not regarded as a full recording night.

**Comment by JimBacon** [comment]
@DavidRoy, do you want to follow Chris's suggestion that the trap definition is part of the site, stored in location attributes? Currently it is part of the sample, stored in a sample attribute.

Also are you in agreement to drop all the options like sugaring and wine roping that we currently have?

**Comment by DavidRoy** [comment]
@JimBacon yes and yes for the SPRING moth trap survey
Thanks

**Comment by JimBacon** [comment]
Closing this issue but continuing with further changes at https://github.com/BiologicalRecordsCentre/ABLE/issues/393
