### ISSUE TITLE
FIT Count website: regional results page not returning any results

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#30]
https://fitcount.ceh.ac.uk/regional-results

**Comment by andrewvanbreda** [comment]
@DavidRoy 
OK I will check, this must be new thing as it was definitely working when it went live

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
Working for me.
Have you got a specific use case that is failing that you can describe?
I tried masquerading as Lars and found it was working also (albeit with no data for 2022 for that region)
Are you expecting more 2022 data?

**Comment by DavidRoy** [comment]
@andrewvanbreda sorry, my mistake as I was not masquerading as a user with the regional co-ordinator role
