### ISSUE TITLE
Moth survey - setup verification/download role for regional co-ordinators

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#32]
Mirror approach used for butterflies
e.g. verification filter setup
https://butterfly-monitoring.net/admin/filters-list

e.g. download page extended to include moth download
https://butterfly-monitoring.net/downloads

**Comment by JimBacon** [comment]
Added a moth trap occurrences download

**Comment by DavidRoy** [comment]
Thanks @JimBacon.  Also need a sample download for moth trap survey

**Comment by JimBacon** [comment]
Added a samples download.

Neither download contains trap and lamp types as these are location attributes which are not available via ElasticSearch.
I can add traditional reports instead to return those when needed.

**Comment by DavidRoy** [comment]
Can you add the sample_comments to the sample download file

It's ok to have the location download as a postgres report.  We do this for the butterfly location information too

**Comment by JimBacon** [comment]
Samples download now rewritten as postgres report in order to includes sample.comment.

**Comment by DavidRoy** [comment]
Can you raise and issue to add sample.comment to the sample ES index.  It looks like sample.comment is in the occurrence ES index?  It appears on this ES report for example - https://butterfly-monitoring.net/elastic/all-records

**Comment by JimBacon** [comment]
Curses. It exists but is renamed from 'comments' to 'event_remarks' in ElasticSearch so I didn't find it. That was a waste of a time. It is back to being an ElasticSearch download again.

**Comment by JimBacon** [comment]
@DavidRoy I don't understand what is required to set up roles.

The download page is accessible to anyone with the downloads permission and that permission has been granted to users with the Scheme Coordinator or Verifier role.

The verification page is accessible to anyone with the verification permission and that permission has been granted to users with the Verifier role.

The verification filters are set up to limit verifiers to countries but I see no limitation on survey or species so these verifiers will have access to both moth and butterfly records I would expect.

**Comment by DavidRoy** [comment]
Thanks @JimBacon. In that case, this is resolved as it fits within the current structure.  If necessary, we could restrict to butterflies or moths based on the filter setup (i.e. restricting to particular surveys).  We may return to this if we need to restrict the downloads by taxon group
