### ISSUE TITLE
Addition sites for MVS map - Czech Republic

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#34]
Additional sites to load.  Sent via email
https://test-eu-pollinator.pantheonsite.io/list-squares

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
Done.
Close when happy.

(Note your URL there doesn't go to a page, I assume you mean this page
https://test-eu-pollinator.pantheonsite.io/list-sites
Although we can change the URL if you wanted)

**Comment by DavidRoy** [comment]
Thanks for resolving this one quickly.  Looks good
