### ISSUE TITLE
SPRING - transect data entry page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#36]
based on:
https://butterfly-monitoring.net/ebms-input-data

**Comment by andrewvanbreda** [comment]
@DavidRoy
I have copied a lot of the configuration across, not sure how mell it will work yet without adjustment.
Is this to use a completely new survey?

**Comment by DavidRoy** [comment]
@andrewvanbreda yes, it will need to be it's own survey under the SPRING website (website id = 140).  Can you clone everything across as a starting point

**Comment by andrewvanbreda** [comment]
@DavidRoy 
We can in theory, but I will check on my machine the behaviour of the clone tool tomorrow.
I think we just want to use the existing attributes with the new survey selected, I suspect the clone tool we create a new set of identical attributes.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
I checked the clone behaviour this morning on Dev Warehouse.
I see 2 possibilities here

1. Use the clone tool.
This literally makes a copy of everything, attributes, termlists etc and imports them into the new survey.
So nothing is reused at all.

or
2. Manually adjust the existing attributes to select them for the new survey.
(This would need some of the termlists to be changed to general Warehouse ownership which I think should be ok, although obviously any adjustment could result in an unforeseen behaviour)

Personally to me, point 2 seems like the more elegant solution.
However, if you think the EU PoMS attributes will be changed out of line with the EBMS ones, it may not be the best solution. Let me know thoughts.

**Comment by DavidRoy** [comment]
I'm happy with option 2 as the two surveys should stay in alignment

**Comment by andrewvanbreda** [comment]
Just to note (mostly to myself), I have tested moving one of the termlists to be Warehouse owned this morning and EBMS behaved fine (Principle Land Management on site details, Location attribute 225, Termlist 836, Indicia Cache Cleared).
Assumption will be that switching to Warehouse control on other termlists will not cause an issue on EBMS either (it shouldn't, but always best to double-check in practice).

**Comment by andrewvanbreda** [comment]
Note (and mainly to myself)
Page now configured, but testing required.
My Walks page also created and configured as the data entry page configuration referred to this.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Think this area is at least good enough now for you to have a check of.
I am aware the order of the attributes is a bit funny, and there are theming issues still.
