### ISSUE TITLE
SPRING: setup taxon lists for transects

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#37]
For butterflies, use eBMS list = 251
For bees and hoverflies, create taxon lists based on recording form.
[SPRING Transect Recording Form - bees and hoverflies.pdf](https://github.com/BiologicalRecordsCentre/SPRING/files/8520566/SPRING.Transect.Recording.Form.-.bees.and.hoverflies.pdf)

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
Three new issues  acknowledged. 
I may contact you with questions shortly.
Let me know priority levels.

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
The PDF talks bout Bumblebee, Hoverfly groups, are those supposed to be separate entries in the new species list?
and are the Hoverflies and Bees supposed to go on the same list?

Actually probably just easier if you let me know the exact entries, then I can create the new list.

**Comment by DavidRoy** [comment]
@andrewvanbreda a single list for bee and hoverfly groups.  The data entry form to have a tab for butterflies and a tab for bee/hoverfly groups

Here are the taxa for the new taxon list.

Bees – Honeybees
Bees – Bumblebees - Group A. Ginger
Bees – Bumblebees - Group B. Black-red
Bees – Bumblebees - Group C. All-dark
Bees – Bumblebees - Group D. Yellow-black-white
Bees – Bumblebees - Group E. Yellow-black-red	
Bees – Other - Large bees (> 10mm)
Bees – Other - Small bees (3-10mm)
Bees – Other - Wasp or blood bees
Hoverflies – Group 1. Large, robust hoverflies (Tribes: Eristalini & Volucellini)
Hoverflies – Group 2. Distinctly bumblebee-like hoverflies
Hoverflies – Group 3. Distinctly wasp-like hoverflies
Hoverflies – Group 4. Hoverflies with black-and-yellow stripes of spots (Core: subfamily Syrphinae)
Hoverflies – Group 5. Other hoverflies

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Close this one if you are happy with it, it has been ready for a while, but I forgot to assign it to you for closing.

**Comment by andrewvanbreda** [comment]
@DavidRoy Further to my email to you this morning, I think this is one that will be best for you to check
