### ISSUE TITLE
SPRING: link pan-trap data entry page to EU species lists

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#38]
The pan trap data entry form to be linked to the EU lists for bees and hoverflies.
Taxon list IDs - 273 and 272

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Deployed to SPRING test site

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Another to close if you are happy

**Comment by andrewvanbreda** [comment]
Superseded by https://github.com/BiologicalRecordsCentre/SPRING/issues/61 which now closed
