### ISSUE TITLE
SPRING: tidy up account registration page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#39]
https://test-eu-pollinator.pantheonsite.io/user/register

- [x] remove picture option
- [x] remove 'Contact settings' section of page
- [x] remove dropdown for 'Your identification experience'
- [x] reword 'Are you happy to be contacted' to 'Are you happy to be contacted about the EU Pollinator Monitoring Scheme and the SPRING project#?'

**Comment by andrewvanbreda** [comment]
@DavidRoy
Done. Close if happy.

**Comment by DavidRoy** [comment]
Thanks
