### ISSUE TITLE
Moth data entry  - counts for inside and outside the trap

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#4]
Two column input for abundance:
count individuals inside the trap
count individuals outside the trap

**Comment by JimBacon** [comment]
If you are proposing that one occurrence record should have two different abundances, this may need careful consideration. 

The cache tables, and hence reports, use the occurrence attribute marked with the system function of sex_stage_count to determine the count of an occurrence. 

If we have two such attributes for an occurrence, the cache builder may not perform as expected. I can't quite figure in my head what the query will do but it might randomly return one or the other.

**Comment by DavidRoy** [comment]
Agreed.  Needs some thinking through.  One option is to submit a single total abundance but capture the separate breakdowns in two additional occurrence attributes?

**Comment by JimBacon** [comment]
Other options include:
* having a checkbox in the species grid to set an occurrence attribute indicating if a record is inside or outside the trap.
* having two input grids, for inside and outside the trap. I guess this would have to set a hidden occurrence attribute.

The database set up and reporting would be identical in both these cases but the latter would be more effort to implement.

We could also create an input grid with two count columns that creates two occurrences behind the scenes. That is not an out-of-the-box solution and would need a couple of days development I should think.

The situation is analogous to recording male and female counts where we choose to create two occurrences distinguished by an attribute for sex.

**Comment by JimBacon** [comment]
The solution implemented is to have 3 attributes: Qty, Qty Inside and Qty Outside.
JavaScript is used to hide the Qty column and to calculate its value from the sum of the other two.
The maths allows for the fact that '0' means absent and ' ' means present but not counted.
E.g. '0' + ' ' = ' ' 
Only the Qty attribute is given the sex-stage-count system function.
