### ISSUE TITLE
SPRING: review moth trap setup

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#41]
Aim to implement moth trap setup within the ButterflyCount app.  Use this as an opportunity to review the current approach to describing moth traps
 
see comment from @larspett linked to issue #33

 @CrisSevilleja @chrisvanswaay to review with Jurien

**Comment by chrisvanswaay** [comment]
I'm not sure I understand this. Should we test this in the app? I tried in the app (v1.15.0(87), but couldn't figure out how.

**Comment by CrisSevilleja** [comment]
I think the review is on the website, review the system of setting up a new trap https://butterfly-monitoring.net/my-moth-traps @chrisvanswaay

**Comment by DavidRoy** [comment]
@chrisvanswaay sorry for not being clearer.  This issue is to check we want to keep the current way of describing moth traps.  Lars had some suggestions on this

**Comment by larspett** [comment]
I find the drop-down list too specific and it will likely grow quickly since there is rapid method development within this field. I suggested that we make the trap description more generic & versatile with some general categories selectable, so that the trap can be described using those categories (and trap model as an optional level of info) For instance:

- trap type
- type of light source, 
- light source power in W, 
- trap model (optional) (if applicable, with a selectable list). 

For instance Heath, actinic, 6W

**Comment by JurrienVanDeijk** [comment]
Good suggestion Lars! So actuelly what is allready there, but split the one row that is there on the arrow? So TL -> actinic -> 6 watt will be 3 different dropdown menu's? Or do you also want to skip the first part?

**Comment by larspett** [comment]
I posted a reply on this on 22-04-25 (suggesting that we close the issue for now) but it doesn't appear here so I am reposting it

> Good suggestion Lars! So actuelly what is allready there, but split the one row that is there on the arrow? So TL -> actinic -> 6 watt will be 3 different dropdown menu's? Or do you also want to skip the first part?

**Hi again,
I think that it might be good with a general overview of the options (including trap type) so maybe stick with the current ones and wait for some more feedback before tinkering with the options. I am not sure what TL means and suspect that many will not know what E27 means. In fact, I suspect that some of the light sources  labelled E27 are actually E39/40, at least our 250 W MV lamps have those sockets. So maybe that categorized part of the dropdown needs to be tweaked a little (bit overall, I think we can keep it for the time being) I am fine with closing this**

**Comment by larspett** [comment]
Hi again,
I think that it might be good with a general overview of the options (including trap type) so maybe stick with the current ones and wait for some more feedback before tinkering with the options. I am not sure what TL means and suspect that many will not know what E27 means. In fact, I suspect that some of the light sources  labelled E27 are actually E39/40, at least our 250 W MV lamps have those sockets. So maybe that categorized part of the dropdown needs to be tweaked a little (bit overall, I think we can keep it for the time being)
