### ISSUE TITLE
SPRING: option to add new MVS sites

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#42]
https://test-eu-pollinator.pantheonsite.io/list-sites

Add option to add new sites to the list.  Not a priority prior to go-live #40

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren,
Would you be able to pull this report onto live please. Cheers
reports/projects/PoMS/get_default_country_for_square.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda  Sorry bit late reponse to this. It's gone live.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
No problem. Thanks
(If I don't mention things are super-urgent you can assume they are ok to put live whenever is good for you)

**Comment by andrewvanbreda** [comment]
@DavidRoy 
This capability is now live.
