### ISSUE TITLE
SPRING site theme

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#43]
Does a theme for the SPRING site need sorting out?

Think just running bootstrap default at moment.

**Comment by DavidRoy** [comment]
@andrewvanbreda yes - good idea.  We agreed with Steve Dixon that we could re-use the UKPoMS scheme.  Maybe a yellow theme to follow the SPRING logo - https://www.ufz.de/spring-pollination/index.php?en=49053

**Comment by BirenRathod** [comment]
@DavidRoy Just to let you know that on UkPoms, the images used are all static. so do you want to use all of them for SPRING project too?
If you want to replace them, send me those new images.

**Comment by DavidRoy** [comment]
ok, which images - how many and which pages are they used on?

**Comment by BirenRathod** [comment]
@DavidRoy 
1. On Home page - Main to bar, also two of "Get involved" blocks and Help gather one
2. On [About](https://ukpoms.org.uk/about) - Main top bar
3. On https://ukpoms.org.uk/fit-counts - Main top bar
4. On https://ukpoms.org.uk/one-km-square-survey - Main top bar
5. and two logos, Main on top and second at the bottom.

**Comment by BirenRathod** [comment]
@DavidRoy Also, Just to let you know ...
As you mentioned based on yellow color theme, I will use this #ffcb00 colour scheme for menu, button, text and social media icons.

**Comment by BirenRathod** [comment]
@DavidRoy  & @andrewvanbreda I have created new theme now and added on to test site. I have also amended color theme as per SPRING project. 

These are things to do as and when needed.
1. The home page's text needs to implement as per SPRING project requirements, so please do so.
2. Once footer text added it will appear automatically.
3. If there is social media link, please add it. for e.g. twitter link.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod @DavidRoy 
Looks much better with the new theme.
It think there are some things about the theme that are restricting functionality.
For instance, with Add Transect it works reasonably well now, but the "S1", "S2" options are actual buttons on EBMS (although they do react on SPRING even if they don't look like buttons).
Also I am finding as I use the functionality, the map is in front and obscuring quite a few of the popups.
Cheers.

test transect here
https://test-eu-pollinator.pantheonsite.io/transect-setup?table=location&id=290122&route-tab=true#your-route

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Would you be able to work out how EBMS is doing the S1/S2 buttons on its theme please? I only have access to checking the html, and it looks same between the 2 sites.
We need SPRING to also be able to use these buttons.
The lack of buttons confused David when he was testing as he assumed they don't work at all when actually they do function, but don't look like it. 
Cheers for any thoughts about getting this working.

![Screen Shot 2022-05-11 at 06 57 28](https://user-images.githubusercontent.com/2463614/167778926-15e51bae-ea7f-4963-958d-7afba9b57c17.png)

**Comment by BirenRathod** [comment]
@andrewvanbreda certainly, I can look into this. Can you send me the URL of the page for ebms site please?

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
This is the one
https://butterfly-monitoring.net/ebms-site-details

However, you will only see the buttons when editing existing data. 
David has a test transect, so you could...
- masquerade as David 
- go to the "My transect sites" option in the My Data menu
- then select to edit the test site grid the grid

The buttons in question can be seen on the Section Details tab.
Cheers

**Comment by DavidRoy** [comment]
@BirenRathod can you also remove the large banner image from all the website pages other than the home page?  It takes up too much room on general pages

**Comment by BirenRathod** [comment]
@andrewvanbreda I have amended the style now for button and some other places.

@DavidRoy larger banner image is part of the way theme design, although I have implemented the code, so that it will only display on first page.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Have you seen a problem where the menu option in the top right isn't always working.
Am logged in and click "Menu" is just displaying a yellow closure cross, all menu items missing.
Doing it on multiple browsers. It seems to only do it after login. I checked and the menu structure on the system does seem to be present. Don't think anything in the Drupal log relating to this.
Cheers for any thoughts

<img width="1045" alt="Screen Shot 2022-05-12 at 10 25 18" src="https://user-images.githubusercontent.com/2463614/168038708-47555832-eb3a-4c40-8a61-86372f650d5d.png">

**Comment by BirenRathod** [comment]
@andrewvanbreda Ahha, Thanks for mentioning this and sorry about this. This happened due to hiding large banner image.

@DavidRoy As I mentioned before the large banner image is part of theme, the way it designed, so I need to re-enable it and make it display again.

**Comment by BirenRathod** [comment]
@andrewvanbreda I have restored the large image again, so you could see menu now.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
No problem, thanks for fix, can see it again.

**Comment by DavidRoy** [comment]
Closing.  Any new problems to be raised as specific issues
