### ISSUE TITLE
Consider SPRING site permissions

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#44]
@DavidRoy 
If you indicate who should see which pages, I will implement required permissions

**Comment by DavidRoy** [comment]
The following for any registered users [we may restrict this later on]:
https://test-eu-pollinator.pantheonsite.io/walk-data-entry
https://test-eu-pollinator.pantheonsite.io/add-pan-trap-samples
https://test-eu-pollinator.pantheonsite.io/ebms-site-details [note that url should change - transect setup page]
https://test-eu-pollinator.pantheonsite.io/my-fixed-square-results

The above plus the following for role = 'Expert entomologist'
https://test-eu-pollinator.pantheonsite.io/select-samples-bycatch-data
https://test-eu-pollinator.pantheonsite.io/select-samples-species-data

The above plus the following for role = 'Regional Co-ordinator'
https://test-eu-pollinator.pantheonsite.io/list-sites
Page to create MVS site #42

**Comment by andrewvanbreda** [comment]
AVB not to myself: All done apart from Regional Co-ordinator

**Comment by andrewvanbreda** [comment]
Just checked site, and regional coordinator does actually have the correct permission for the list and edit sites page (Add Site page not yet added, but that will be based on Edit Sites anyway).
Have tested a few roles and looks ok per specified

**Comment by andrewvanbreda** [comment]
Am closing this

@DavidRoy 
Have noticed that, unlike FIT Count, no specific  country is specified for a regional coordinator on SPRING (they just have access to the full sites list for all countries).
If this is incorrect, please raise as another issue.

**Comment by DavidRoy** [comment]
Thanks.  The permissions are ok for now.
