### ISSUE TITLE
Squares to be filtered by country on pan-trap form

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#46]

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Whenever you get a moment, would you be able to pull this report onto live please. 
Cheers

reports/projects/PoMS/get_default_country_for_sample.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda This report gone live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod That is great thanks Biren, looks to be working.

@DavidRoy The pan-trap form should at least be good enough for you to have a nose around now and let me know your thoughts.

**Comment by andrewvanbreda** [comment]
AVB not myself: Just noticed square does not default correctly if there is more than one available in edit mode, so need to fix that.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Would you be able to pull this report onto live please whenever you get a sec, thanks as always
projects/PoMS/get_default_locations_for_sample.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda did you commit onto master branch? I just pull it but nothing happened.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Thanks for letting me know, yes you right there it hasn't pushed.
I have fixed it and can now see it on github.com, so should be fine to pull

**Comment by BirenRathod** [comment]
@andrewvanbreda  Thanks, Gone live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks for quick response, have just checked that and it is working fine.

Closing
