### ISSUE TITLE
Transect Setup - MVS square not defaulting in edit mode if more than one available

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#47]
Zoom to square not occurring in edit mode on Transect Setup page

**Comment by andrewvanbreda** [comment]
Note sure zoom problem is real, think might be old version fo Safari.
However there is a defaulting problem as per issue title.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Would you be able to pull the following report onto live whenever you get a moment please.
Thanks

reports/projects/PoMS/get_default_locations_for_transect.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda I have pulled down that report now. Sorry for bit late response to this.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
No problem. Thanks :)

**Comment by andrewvanbreda** [comment]
Fixed defaulting. 
Zoom problem still occurring but will raise separately
