### ISSUE TITLE
Transect Setup - Error on save because location code is often too long

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#48]
Hi @DavidRoy 
In testing I have noticed an issue on Transect Setup.

On save I get an error.

The reason is the code is a maximum of 20 characters in the database, however the requirement for the field is "Site name - transect name"
Please advice on preferred solution.
We are limited by database field length.

**Comment by DavidRoy** [comment]
@andrewvanbreda ok, leave this as a free text field.  Can you add some help text to explain that Transect name is restricted to 20 characters

**Comment by andrewvanbreda** [comment]
@DavidRoy done
