### ISSUE TITLE
Transect Setup - Zoom to square not occurring in edit mode

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#49]
Works on my own machine however

**Comment by andrewvanbreda** [comment]
Zoom changed to level 16 (3rd strongest zoom) upon request.
Although still not working on test site.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Have temporarily switching to OpenStreetMap as default layer.
The problem is occurring with the Google Map set as default. Am not sure why this is happening but it isn't SPRING specific as the simple Add Location form on my machine does same thing.
I am not sure that it wouldn't actually affect EBMS if it was setup in the same way, but that has Open Street Map as default so wouldn't see same issue.
Have asked John if he has seen this before, so awaiting response.

That explains why the zoom was ok on my machine, as I had a different default layer.

Note: I am aware of another issue which causes incorrect zooming after square is changed, but I will await John's response first, it may be related.

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
John got back to me about this.

This is what he says:
"Yes, that's what happens. Google Maps only loads when actually demanded, because otherwise Google counts it as a hit (and hence it costs money) even if you don't zoom in enough to show the Google Satellite layer. Are you able to work around it?"

David: I suppose my first question to this is, is Google necessary as the default? (actually it isn't on EBMS).

Otherwise I will have to find a way around this (which is obviously the more expensive option).
One way may be to actually default to Open Street Map, then switch to Google Hybrid automatically a second or two later.
Although as John notes, this will take more Google hits.

**Comment by DavidRoy** [comment]
@andrewvanbreda - defaulting to Open Street Map is fine, with google hybrid an option in the map controls?

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Done, have done that with all maps on the site for consistency.

I will close this issue as I am one who opened it. Mail me if you don't want all maps to be setup same way.
