### ISSUE TITLE
Enable login via email for pollinator monitoring scheme website

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#5]
https://test-eu-pollinator.pantheonsite.io

enable login via username or password

**Comment by BirenRathod** [comment]
@JimBacon there is a nice module called Superlogin which does this.

**Comment by JimBacon** [comment]
Thanks @BirenRathod. That module was already installed so I just had to enable it.

As an upshot of testing, I also made Last Name a required field as the registration with the warehouse depends on it.
