### ISSUE TITLE
SPRING: site theme differs by browser

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#50]
The banner image is different on Chrome versus Edge.  The Chrome version is better as a more zoomed in.
Chrome screenshot
![eupoms-chrome](https://user-images.githubusercontent.com/2699478/167819218-1d7cbe06-ff0d-4129-8708-b65e8a702667.png)

Edge screenshot
![eupoms-edge](https://user-images.githubusercontent.com/2699478/167819330-00c5e6ad-4c85-49f8-8ad5-d956039ea30b.png)

**Comment by BirenRathod** [comment]
@DavidRoy  On edge, it is using images from cache, that was a old images. so please clean cache of browser.

**Comment by DavidRoy** [comment]
@BirenRathod clearing the edge browser cache did not change the image

**Comment by BirenRathod** [comment]
@DavidRoy Definitely browser's cache problem. I don't see that. you can try loading in 'New InPrivate window' of browser.
See below my screenshot from edge. 
![image](https://user-images.githubusercontent.com/5941255/167826114-d42eec37-76b0-4393-9eb8-10a44de4b02f.png)

**Comment by DavidRoy** [comment]
ok, will close for now and check again when site is live
