### ISSUE TITLE
SPRING: Transect setup page (restrict list of countries) and pan-trap entry page - restrict country drop-down lists

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#51]
For 
https://test-eu-pollinator.pantheonsite.io/transect-setup
https://test-eu-pollinator.pantheonsite.io/add-pan-trap-samples

Restrict the country drop-down to participating countries only
Austria | AT
Belgium | BE
Bulgaria | BG
Croatia | HR
Cyprus | CY
Czechia | CZ
Denmark | DK
Estonia | EE
Finland | FI
France | FR
Germany | DE
Greece | GR
Hungary | HU
Ireland | IE
Italy | IT
Latvia | LV
Lithuania | LT
Luxembourg | LU
Malta | MT
Netherlands | NL
Poland | PL
Portugal | PT
Romania | RO
Slovakia | SK
Slovenia | SI
Spain | ES
Sweden | SE

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Done for both forms, although note that I included United Kingdom also for now, as that is where our test squares are. It is a 5 minute job to remove that entry and I have made a note to remove that before go live.
Please close this particular issue once happy

**Comment by DavidRoy** [comment]
@andrewvanbreda - yes, including UK for testing is a good idea
Restriction to countries also needed on:
https://test-eu-pollinator.pantheonsite.io/walk-data-entry

**Comment by andrewvanbreda** [comment]
@DavidRoy Done

**Comment by andrewvanbreda** [comment]
Close if happy

**Comment by DavidRoy** [comment]
Thanks, closing
