### ISSUE TITLE
SPRING: walk-data-entry layout

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#52]
Improve layout of walk-data-entry form. @BirenRathod can you take on this design improvement?
https://test-eu-pollinator.pantheonsite.io/walk-data-entry?

The current page is like this:
![spring walk-entry](https://user-images.githubusercontent.com/2699478/168566722-c5843fd5-cdd6-48c1-9455-c01ed3f02f31.png)

Ideally it would match the compact form of the ukbms:
![ukbms walk-entry](https://user-images.githubusercontent.com/2699478/168566836-51d96dad-eb4b-4a4b-b9e2-141a5176653a.png)

Otherwise, the ebms layout would be ok. 
 ![ebms walk entry 2](https://user-images.githubusercontent.com/2699478/168587269-8c346f60-0004-4093-99e0-c0c857a61c13.png)

The most important thing is the order of the data entry fields: start time, end time, %Sun, Temp, Wind direction, Wind speed, Notes

**Comment by DavidRoy** [comment]
@BirenRathod can you also fix the theme for the buttons at the bottom of the page.  

It looks like this on the first page
![eupoms - button1](https://user-images.githubusercontent.com/2699478/168639551-26e34f50-ffaf-431f-9725-2149a4046788.png)

And this on the second
![eupoms - button2](https://user-images.githubusercontent.com/2699478/168639615-516ec89d-7899-41fa-8e8a-66fc4d6d4332.png)

**Comment by BirenRathod** [comment]
@andrewvanbreda I have resolved the css style problem on this _> https://test-eu-pollinator.pantheonsite.io/walk-data-entry. 
Can you re-order those attributes which David has suggested here? It will be easier to do for you than me.

**Comment by BirenRathod** [comment]
> @BirenRathod can you also fix the theme for the buttons at the bottom of the page.
> 
> It looks like this on the first page ![eupoms - button1](https://user-images.githubusercontent.com/2699478/168639551-26e34f50-ffaf-431f-9725-2149a4046788.png)
> 
> And this on the second ![eupoms - button2](https://user-images.githubusercontent.com/2699478/168639615-516ec89d-7899-41fa-8e8a-66fc4d6d4332.png)

@DavidRoy Margin and size of buttons have been implemented now.

**Comment by DavidRoy** [comment]
Thanks Biren - much better.  
@andrewvanbreda let me know when you've sorted out the attribute order

**Comment by andrewvanbreda** [comment]
@DavidRoy @BirenRathod 
Ok, I will have a look again how this is working in the EBMS code.

**Comment by andrewvanbreda** [comment]
@DavidRoy @BirenRathod 
Have used the survey attribute layout editor in the Warehouse to match this up with EBMS.
The attributes are drawn left to right, on a row to row basis after the Date. However this does means that the Recorder Name attribute is appearing to the right of the date.
This is consistent with EBMS (apart from we are using two columns), but it is not consistent with that UKBMS screenshot.
Let me know which way around they should be, if it they are supposed to be the other way around, I will have to write some jQuery to switch them I think.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Unfortunately the layout seems to have broken again, particularly adding new walks.
I think it became broken again as some things changes on the page.
Could you let me know where you added the stylesheet changes to fix the previous layout (or if you can fix this easily that would be even better).

See screenshot.

Cheers

![Screen Shot 2022-07-15 at 09 41 33](https://user-images.githubusercontent.com/2463614/179188291-32ddc073-ccac-4556-b492-6cf02a0c1aa4.png)

**Comment by BirenRathod** [comment]
@andrewvanbreda I have amended style and js file, so it should display much better way. you can find those files are node.29.js & node.29.css in files/indicia folder. 
There are still some chnages needed but I will do some other time but atleast it is in presentable form. Also, fields in "Transect walk type" display should be inline with each other. not sure are you thinking same way or not?

**Comment by andrewvanbreda** [comment]
Hi@BirenRathod 
Thanks for doing that, looks much better than it did. I will make some further adjustments later, so the right-side is shift down one so the time comes out on one line.
Ah yes ok, thanks for letting be know they are in node specific files, that is good place for them.
As those aren't under git control I always commit a copy to support files, so I will commit your changes there.
Yes I see what you mean about those labels, I didn't notice that before. I will fix them later.
Leave this issue open for now.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Have many further adjustments to the way the page looks.
Awaiting any further comments.
Note the page does have several modes, so worth looking at both new walks and editing existing

**Comment by DavidRoy** [comment]
Thanks for improvements
