### ISSUE TITLE
SPRING: add banner to website design

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#54]
The website lacks a page banner. https://test-eu-pollinator.pantheonsite.io/

Please add one to the website theme, following the one on UKPoMS but
- change colour to match theme
- change logo to SPRING
- remove (c) text
- keep link to a Terms of use and Privacy page

PoMs banner:
![poms banner](https://user-images.githubusercontent.com/2699478/169019439-01e5c228-d6b7-420d-a3a7-30c8addff80e.png)

**Comment by BirenRathod** [comment]
@DavidRoy right that is footer which I mentioned [here](https://github.com/BiologicalRecordsCentre/SPRING/issues/43#issuecomment-1113566169) It will come up automatically once text or link added.

**Comment by BirenRathod** [comment]
@DavidRoy link, logo and copyright text added on to footer now.

**Comment by DavidRoy** [comment]
@BirenRathod Thanks.  Can you also add a link titled 'Credits and partners' that links to this page: https://test-eu-pollinator.pantheonsite.io/credits-partners

**Comment by BirenRathod** [comment]
@DavidRoy done.

**Comment by DavidRoy** [comment]
Thanks
