### ISSUE TITLE
Habitat information to be recorded for transects?

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#56]
Hi @DavidRoy 
I recall at some point we discussed about saving habitat information for transects. Am sure we said not to use the existing EBMS habitat fields and to replace them with the pan-trap habitat field?

Is that the case?
I cannot find information about this in Github, but it is something we would want to clarify before live. I suspect we might have spoken about it over Zoom and it wasn't recorded.
I think the habitat fields in EBMS are held on the transect site, but on pan-trap it is held on the sample.
Are you able to confirm
1. If we need this at all?
2. Is the habitat field to go onto the site, or saved on the sample (walk)?

**Comment by DavidRoy** [comment]
1. not for now
2. it would be part of the location (site) attributes, not the sample (walk)

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Ok thanks for letting me know. Will leave for now then.

**Comment by andrewvanbreda** [comment]
Not needed for now, so closing
