### ISSUE TITLE
Confusing instructions during registration

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#57]
The registration process works, but I found it a bit confusing.
However I don't see how the problem I saw could be unique to SPRING, nor am I sure of how to fix it.

@BirenRathod Have you seen this before? and do you know if there is an easy solution?

After you use the link on the registration email, you change your password, but even after you save it the following message continues to display on the page (I think ordinary users would find this very confusing as they have already changed their password.)

"You have just used your one-time login link. It is no longer necessary to use this link to log in. Please change your password."

**Comment by BirenRathod** [comment]
@andrewvanbreda Yes, I have seen this. This has been introduced in Drupal 9. not sure I can offer any solution here.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks for thoughts. I will leave this issue open for a bit to see if I can think of something (perhaps getting at the text and rewording it). Otherwise might end up closing this and hope it gets fixed in a Drupal update.

**Comment by andrewvanbreda** [comment]
Going to close this, hopefully this will be fixed with Drupal update
