### ISSUE TITLE
SPRING: place name search box needs to work outside of the UK?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#59]
https://live-eu-pollinator.pantheonsite.io/transect-setup
The place search above the map seems to be restricted to the UK?  e.g. Madrid does not return a location?

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Have cleared United Kingdom as being the preferred georeferencing country. Close if happy. Madrid now work.
