### ISSUE TITLE
Create My Results/Download page on FIT Count site

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#6]
The FIT Count site should have a My Result/Download facility for app data.

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy ,

Did you want to have a check of this page. Pending your checks it should be ready to go live.

https://fitcount.ceh.ac.uk/my-results

You should be able to masquerade if you need more data to see.

There are a few differences with UK poms.
There is no Edit button (as with can't support that yet with all the term sets we discussed).
I set the map to Zoom to output. If the user has no results it is roughly placed over the EU area.
I removed the survey column which is always the same for the app, I also removed the location column as it is always empty for app data.
Although both are in the download.
It is probably best to leave the survey column in the download, but the location column is probably best removed. 
I can change that before go live (although I will wait to see if you have any other comments first so I can do any changes all at once).

I did just notice there is one known issue that is same as UK PoMS.
The Habitat column shows "Other - please describe below" sometimes.
Actually this works in the Target Flower column (e.g. which would display "Other (Hibiscus)")
This will get fixed when I get a chance. If you want this fixed before go live let me know.
It isn't too difficult so could probably adjust that today actually.
It wasn't fixed on UkPoMS quickly because I ran out of budget, but could just put this on the EU project timesheet.

So ignoring the location column, and that Habitat column problem, could you let me know your thoughts on the rest of it.

Download is accessed from bottom right of the grid.

**Comment by andrewvanbreda** [comment]
Have removed the Location column and fixed the Habitat column.
I won't get Biren to re-pull the report until you have checked it for any other changes.

**Comment by DavidRoy** [comment]
looks good to me, thanks

**Comment by DavidRoy** [comment]
@andrewvanbreda can I check the values are correct in the download.  I masqueraded as https://fitcount.ceh.ac.uk/user/1 and clicked on the download link at the bottom right of the data grid.

The column 'Flowers counted' has some odd values such as: 'Cleveland', 'City', 'Master' etc.  It looks like there's some odd terms being picked up?

**Comment by DavidRoy** [comment]
Also, will the 'Country/Island' work outside of the UK?

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Thanks for these notes. I will check what has happened there tomorrow, sounds like perhaps an incorrect ID number has been entered or something.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Countries currently detected are:
England
Scotland
Wales
Northern Ireland
Isle of Man
Jersey
Guernsey
Cyprus
Argentina
Brazil
Chile

Which I think are the areas currently active for the app?

I have a note to allow a complete list of countries, but I need to change way report works, as it was originally just designed for the small number of countries associated with the UK PoMS site. I need to change it so it can take a set/array of countries.

Thanks for spotting the other problem. This is a bug in the report.
I can see why it crept onto the FIT Count page, that is simply because the report that page is using is a slightly modified version of a UKPoMS one, and I had assumed that was working correctly as no problems had been reported with it.
I will fix that for both EU and UK PoMS

**Comment by DavidRoy** [comment]
We'll need a list of all countries in Europe in addition to the current list.  We may also want to consider going global at this stage? @JimBacon might want to input to this discussion

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
If you let me know if this needs removing for the time being? as I will need to delete it (comment out) from report (as hiding it will still show in the download).
If you let me know then I can commit that at same time as other fix.

**Comment by DavidRoy** [comment]
@andrewvanbreda yes, best to remove this field from the download file.  The wider issue of country boundaries is more relevant to #8

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 

Could you pull the following PoMS report when you get a chance (or the whole folder if you prefer)
poms_results_in_detail_mapping_admin_lingual_3
poms_results_in_detail_admin_lingual_3
my_poms_results_in_detail_mapping_lingual_2
my_poms_results_in_detail_lingual_3_extended_temp
data_download_in_detail_with_blur_lingual
blurred_poms_results_mapping_lingual_3
my_poms_results_in_detail_lingual_3

They are live reports, but have checked they don't error on my own machine.

Cheers.

**Comment by BirenRathod** [comment]
@andrewvanbreda  they all gone live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Great, thanks for quick response Biren.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
The Flowers Counter problem is fixed.
The Country is removed for now.
Did you want this page to go live?

@kitenetter
Not the problem David noted with the Flowers Counted is also fixed on UKPoMS

**Comment by DavidRoy** [comment]
Looks great @andrewvanbreda.  Please make live

In addition, please make these small minor changes to the download:
- Change column label [Grid ref] to [Spatial reference]
- can the photo be a full url?  Otherwise, this column is of no use?

**Comment by andrewvanbreda** [comment]
@DavidRoy 
I think the photo column can't be changed, as it is just what was used by Indicia to actually collect the photo in the grid, so change that would stop the photo from showing.
Also the path wouldn't be useful, it would just show a path on the Warehouse to a randomly generated filename.
What is really needed I think is functionality in Indicia to remove the column from the download file. I don't think we have that although I will double-check again as have now had a few projects suggest such a thing would be useful.

The label would need to be changed in the report the way things currently work (as the download file doesn't repeat label changes in the grid).
I can do that as I created a separate temporary report for now.
However it would be better if we can share the reports with UKPoMS and the term request by Martin/Claire on UKPoMS is Grid Ref.
This should probably be consistent between the projects?

I am wondering if now might be the time for to look into a possible fix for the two problems I just mentioned. I never looked at it in any level of depth.
- The ability to remove columns from the download file
- The download file should use the labels used in the grid. If that were the case I could share UKPoMS reports but still use different column label names.

Have now put the page live.
It is in the top-right account menu, as it looked odd on its own in the main menu (which currently only has Home in it)

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod,

Would you be able to pull the following reports please whenever you get a chance, fine to wait until next week if needed. Will just allow me to fix a couple of the things David mentioned (also perhaps lead to some speed up on UK PoMS if this works)

my_poms_results_in_detail_lingual_3_extended_temp
my_poms_results_in_detail_lingual_3_extended_temp_download

Thanks

**Comment by BirenRathod** [comment]
@andrewvanbreda gone live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren for quick response

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Ok, the download is now driven by a different report, so have removed photo column from download. Also Grid Ref column name changed.

**Comment by DavidRoy** [comment]
Thanks Andrew.  Closing this now
