### ISSUE TITLE
SPRING: pan trap entry form, lacks plant species list?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#61]
https://live-eu-pollinator.pantheonsite.io/enter-pan-trap-results-fixed-square-survey

The species lists are for hoverflies and bees.  This page should have a list of plant species for flowering information (as on UKPoMS)

![eupoms - pan](https://user-images.githubusercontent.com/2699478/169401541-3f314ee0-2000-4090-938d-a9d943cf656b.png)

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
Ok can do that. 
But where I the hoverfly and bee species lists we spoke about supposed to appear on the system?
I think I have been confused by #38

**Comment by DavidRoy** [comment]
This page needs to be and hoverfly lists
https://live-eu-pollinator.pantheonsite.io/species-data-entry?sample_id=18461321&implicit=f

Same approach as uk poms?

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Ah yes I understand now.
Ok, will deal with that early tomorrow.

**Comment by andrewvanbreda** [comment]
Main pan-trap form updated so general visitors won't see anything wrong, will do rest tomorrow.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Corrected, close if happy

**Comment by DavidRoy** [comment]
Thanks!
