### ISSUE TITLE
SPRING: Pan trap number lacking from results report

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#62]
https://live-eu-pollinator.pantheonsite.io/my-fixed-square-results?table=sample&id=18461321
Pan number column is blank

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Good spot.
Fixed, the problem was that most of the pan-trap form is shared with UKPoMS, but the pan-trap station numbering is different.
The report was still pointing at the UKPoMS attribute and I hadn't noticed.
Also fixed elsewhere on the bycatch/insect pages. 
Close if happy.
