### ISSUE TITLE
Add/Edit MVS Square page does not load

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#63]
Javascript errors

[Error] SyntaxError: Unexpected token '='
[Error] TypeError: undefined is not an object (evaluating 'drupalSettings.bootstrap')
[Error] ReferenceError: Can't find variable: indiciaData

**Comment by andrewvanbreda** [comment]
https://pollinator-monitoring.net/edit-square

Notice javascript errors and map fails to load

**Comment by andrewvanbreda** [comment]
Hi @JimBacon ,

Hope all good with you.

Are you able to shed some light on this?

The problem seems to be caused by this line which is part of the commit below

intersects ||= parentFeature.geometry.intersects(editFeature.geometry);

https://github.com/Indicia-Team/client_helpers/commit/ca4b5df7e01064f12cee4a30663ab49ab9188907

I think I have seen this same error on other pages using dynamic_location recently.

The location page isn't using parent locations, so am not sure what is happening in regards to this line getting called.

Cheers for any thoughts regarding this.

**Comment by JimBacon** [comment]
Hi @andrewvanbreda 
When I visit https://pollinator-monitoring.net/edit-square the map loads and there are no errors..
<img width="635" alt="Capture" src="https://user-images.githubusercontent.com/2545390/172146077-c84654d6-a768-436c-8229-77331bd24658.PNG">
.

**Comment by andrewvanbreda** [comment]
@JimBacon 
Thanks for letting me know. 
I see now it is this Safari browser I have. 
I will stop using it, as I just remembered we had a similar problem before for NPMS, and we decided that we didn't need to support this version of Safari.
Closing
