### ISSUE TITLE
Pan trap form - Missing "Cast shadow" attribute

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#65]
"Cast shadow" is mentioned on the website and in the field manual, but not on the field pan trap form, so the pan trap form should be updated.

Correction instruction from David: 
Could you add this new sample attribute to the survey setup and recording form as a Boolean field

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
I checked the website and a cast shadow field is already on there, however it is not a boolean.
Are you able to confirm as I am now confused how to proceed.
![Screen Shot 2022-06-14 at 18 41 16](https://user-images.githubusercontent.com/2463614/173648213-4d7b4fb7-bfee-460e-8405-f9875f168068.png)

**Comment by DavidRoy** [comment]
@andrewvanbreda I've realised what the problem is with this.  The paper recording forms (not the web forms) do not include this attribute.  Given we are mid-way through the season, I suggest we hide this attribute from the recording form for this year - to avoid confusion.

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
Done.
Feel free to close, although if you think we might need this next year then perhaps one idea is to leave this open as a reminder.
