### ISSUE TITLE
Transect form - Separate bee/hoverflies and butterfly forms

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#66]
People walk the bee and butterfly transects separately, but data on the website is submitted on the same form.

Correction instruction from David:
Create two separate transect input forms: one for bee/hoverflies and one for butterflies.  Each only has a single tab for entering the counts

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy

I have looked into what to do with this issue.

I can see a number of problems here which makes me concerned the suggestion is more complex than what might be necessery.

For instance,
What to do when a user clicks on the new walk icon for a day.....we could show a popup asking the type of walk.
When clicking existing samples we would need to direct them to the different forms based on the input_form column in the database, this would also mean leaving the old form in place in the background so it can be opened for existing samples.
Having to duplicate future enhancements, and test the same thing on more than one form.

Of couse all of the above is doable, however I am wondering if it is actually the right thing to do.

I think there is a big question about this....and it is one I can't answer myself.
That is this.

Are the samples attributes likely to vary between the forms in the future?

If the answer is the attributes are the same, and will stay the same, I would suggest the following. 
Add a radio button selection attribute on the form itself, which would show the correct species grid when selected.
This is then saved as an attribute and we can hide/show the correct grid based on its selection.
(this also works for older samples which would not have this filled in, so we could show both grids until the user edits the sample)

The obvious advantage to this suggestion is we have the simplicity of one form.

To be honest, at the minute they can still create two samples for the 2 walks no problem, although this could make things clearer.

Let me know your thoughts, feel free to explain if you still think 2 forms is better, which might be the case if you think the sample attributes will vary.

Andy

**Comment by DavidRoy** [comment]
Thanks for looking at this.  The sample attributes are the same.  Your suggestion of a radio button selection to select the taxon group sounds good to me.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
This one has been deployed to live

**Comment by andrewvanbreda** [comment]
Closing, reopen if needed.

**Comment by andrewvanbreda** [comment]
Closing, reopen if needed.
