### ISSUE TITLE
Transect form - Default form to ‘Species recorded from this site’ for the data grid

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#67]
Problem
All European butterfly species are on the same page. Maybe easier to have a drop down menu similar to the plants in the pan trap form. 

Correction instruction from David
Could the form default to ‘Species recorded from this site’ for the data grid

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
Do you mean the "Species known at this site" drop-down option?

Another thought.
Could the sort order field for species in the database be used to bring more common species closer to the top of the list or group them by the categories you want?
Currently we have the sort order defaulted to "Taxonomic Sort Order" but when I looked, I noticed that the field was not filled in the database for these butterfly species.
(actually am not sure how it orders them if the sort order isn't filled in)

**Comment by DavidRoy** [comment]
@andrewvanbreda I meant 'Species known at this site'.  So those recorded before.  This could also include ordering by most common if performance was not affected

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
I have set that option to be the default.
(As that is an option that has come across from EBMS, I will assume it is fully working, but I did try some basic tests with one one previously recorded row and it seemed fine)

As the forms are based on EBMS, I am not familiar with all the code, so actually the sort order is as much of a  mystery to me as to you. 
I do notice that if you switch away from taxonomic sort order, then back again, it isn't actually the same order, which is sign that perhaps it isn't ordering to particular logic.
I think it would be quite tricky to force the previously used ones to be at top of the list when the user switches to the full list option.

I think I can offer two options.
1. Use jQuery to order by species name, then hide the ordering control, also with jQuery. See screenshot to see what grid looks like with this option on

![Species name](https://user-images.githubusercontent.com/2463614/193602349-d8d61db9-5a5d-4473-b2e8-749764b8f264.jpg)

2. 
We can switch on the "Disable Taxonomic Sort Order" configuration option, again this is inherited by EBMS, that option description is as follows
"Some lists (e.g. the full UK Species List) may not have the taxonomic sort order filled in. In this case, there is no point in sorting by the TSO. The default will be the next available SO from the list common name, preferred taxon, taxon."

and results in the grid being ordered as shown in this screenshot.

![Taxonomic Sort Order](https://user-images.githubusercontent.com/2463614/193602934-10d404fd-9096-4059-83a9-8de83d755d7b.jpg)

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Just a further note on this, obviously that second list might look odd if Common Name isn't displayed. If that is interest to you, I can look into adding the common name to the rows (this isn't obvious in the configuration, but I see EBMS forms have quite a lot of configuration capability).

The other option I have just noticed is that there is a "Common Species List" option that can be configured. If the use selects this, I think it displays another species list which I assume would be a subset of the main species list.
Obviously we would need to define the species to go into that list, but I think it is an option if you want to display fewer species.

Sorry slightly vague answers, but I am still learning about a lot of the EBMS functionality we are inheritting
also.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Closing this now.
Have changed system so that Butterflies is alphabetic (as suggested by user in Web Review document)
The other drop-down now defaults to Species Known At Site.

Bee/hoverfly tab changed to ordering as per paper form (using taxonomic ordering).

There is just one small bug not sure is directly caused by website, where there are two unordered items appearing at top of butterfly list for some reason, even though rest of order is correct. I will raise this separately to deal with.
