### ISSUE TITLE
Transect form - Drawing transect segment option not available

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#71]
User experiencing issue where there is no option to draw the transect segments on the map. The submitting form works, but they cannot draw anything.

David to review guidance to find out what the issue is.

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
I assume this is the same issue as the zoom video example.
I do not get the problems your colleague is experiencing. I am using Mac Chrome (I don't have Edge, although they got the same problem on Chrome)
However there are some oddities with that video, I wonder if their Javascript is caching old code.
For instance, on the first tab in the video the Site Code is read-only, That is no longer read-only on the system. 
Also the yellow explanation text is missing from the second tab, not just the drawing controls.
Is it just one user who has this issue or several?

The other possibility is that, although my page is running, it is giving a general error that looks like it is originates in the core Indicia code, so it might be my browser is continuing regardless, and theirs is stopping.
Although that does not explain the read-only Site Code.
It might be worth getting them to clear their browser caches.....I suppose there is a chance both of their browsers are caching old code.

**Comment by andrewvanbreda** [comment]
Further note, that error is just a minor one and not the cause, it only occurs when leaving first tab and returning to it (although I will still correct it).

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
I have just switched on a permission (Ajax Proxy) that should of been on that I noticed was off.
Although I can't say if this will have any practical affect on your colleague, it is probably worth them trying again and at the same time clearing browser caches.
Let me know if that helps.

**Comment by DavidRoy** [comment]
@andrewvanbreda still a problem.  Message from colleague:
I just have tried again (also erasing cookies) and still does not work. 
The tools to draw the subtranssects do not appear, it looks like this:

![spring transect](https://user-images.githubusercontent.com/2699478/180991758-ba78fb36-b756-42c9-8398-917e3c672064.png)

**Comment by DavidRoy** [comment]
I have replicated the problem by masquerading as https://pollinator-monitoring.net/user/15

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Ok thanks for the info. I will look right now.

**Comment by DavidRoy** [comment]
Thanks @andrewvanbreda.  Maybe see if you can create transects for Spain. It could be an issue with the region or user accounts?

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Thanks for the masquerade link. 
Yes I can see that user has an issue.
My initial thinking could be permission issue with the roles, I will examine the system now.

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 

The problem is not a Drupal permission, but a permission within the form.

As you know, the forms are based on EBMS, and that has a complex permissions system.
So there is a bug in the conversion from EBMS style permissions to SPRING.

I have changed it so it will only ever been in read-only mode if a walk has been created for the transect already.

I have made a note to myself to examine the code and clean this area up as the short development time mean it is not as elegant as it could be, there is a lot of ebms stuff in there that isn't needed now.

Please try again, but i can see it working for the user you suggested masquerading as.

**Comment by andrewvanbreda** [comment]
Please close this issue if happy with outcome, or comment further.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Note in EU PoMS there are no country specific permissions. There is no permission where you can create Transect for one country but not another.

**Comment by DavidRoy** [comment]
Now working, thanks!
