### ISSUE TITLE
Transect - unable to edit https://pollinator-monitoring.net/transect-setup?id=294516

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#77]
@andrewvanbreda I think this transect might have been setup before you fixed the route drawing.  It needs to be edited to draw the transect route but this is not possible.  The transect has data associated with it so we cannot delete this one and start with a new one.  Please can you advise on the options to resolve this.

Also a problem with Schafstädt transect

**Comment by andrewvanbreda** [comment]
@DavidRoy I will look now.

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
The system is actually performing as I intended (which may of course be different to what you want).

What has happened is the transect is locked from editing because it has walks associated with it.

Please advise.

1. Change that logic.
2. Or we can delete the walks and I think it should become editable again.

**Comment by DavidRoy** [comment]
thanks @andrewvanbreda 
The logic is ok but because of the bug with this page, the walks were entered before the route was setup.

I think it's simplest to change the logic and allow transect routes to remain editable, even after walks have been submitted.  Is that feasible?

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
Yes, just double-checked the code. I can edit 2 lines of code I think, then we can reintroduce the logic at a later date if you wish. 
I will do that now and let you know when done or if I hit a snag.
Andy

**Comment by andrewvanbreda** [comment]
@DavidRoy 
I have made the change and can see the editing tools for that transect now and also Schafstädt

**Comment by DavidRoy** [comment]
Thanks
