### ISSUE TITLE
Deploy pan trap additional data forms

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#78]
Hi @DavidRoy 

The Add Insect Bycatch Data form and Add Insect Species Data are both ready, however I am not sure about your request to not have access control on the pages.
That would mean anyone could register with the site, and add all the data they wanted to those pages, and I think they would also be able to edit and destroy data.
That seems problematic to me, although if you do really want their to be no role restriction I will go ahead with that if you really want.
Please confirm.

**Comment by DavidRoy** [comment]
The only access control is to allow registered users to enter data.  I think it very low risk that others would add data, and we can implement access controls at a later date if required

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy
This is now deployed for authenticated users.

Previously this has been setup for the "EXPERT ENTOMOLGIST" role only.

Ignore the following notes, they are intructions for me to go back to that role only if needed.

For the bycatch pages:
Set "bycatch-data" as the permission for
"Permission name for view access control" for both the report page and editing pages
"Permission required for viewing other people's data" on the editing page only
"Permission required for editing other people's data" on the editing page only

For the insect species pages:
Set "species-data" as the permission for
"Permission name for view access control" for both the report page and editing pages
"Permission required for viewing other people's data" on the editing page only
"Permission required for editing other people's data" on the editing page only

**Comment by andrewvanbreda** [comment]
Close issue if happy, or add further notes.

**Comment by DavidRoy** [comment]
@andrewvanbreda can you confirm that the species lists are the SPRING/EU ones?

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
Bycatch form is using the following, which looks like is shared by PoMS projects. Not quite sure who originally created it, the stamp just says "support" created.
"Insect groups (PoMS pan-traps)" (species list 234)

Insect species is using the following lists which look like they were created by Jim for the EU Pollinator Monitoring Scheme.
"Syrphidae in Europe" (species list id 272)
"Bees in Europe" (species list id 273)

**Comment by DavidRoy** [comment]
Thanks, that's right
