### ISSUE TITLE
Transect drawing - user interface improvements

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#80]
Drawing out transects on the map
When dragging and dropping a transect on the map, it would be very useful if you can see the length while dragging the line across. We now have to guess, then save the line, return to another screen to check and go back in to redo it if the distance is not correct. Sometimes we had to repeat this several times to get it right.

Also take into account this volunteer's observation
"The manual introduction of the sections one by one without a coordinate search bar is tedious and not precise. Additionally, with the google hybrid layer, which is the most familiar view, the coordinate numbers appear small and get lost with the background. I found the yellow instruction box added before the map, really aiding, especially the double tap tip."

**Comment by andrewvanbreda** [comment]
Also consider this
"It is a little difficult with the calculations of the length for each subtransect because it must be saved each time. However, when it went back to the setup it brings you to the first view of the spring site. Could be possible to go back to the same zoom and location the last time was edited?"

Although maybe tricky, might need cookies and things.

**Comment by andrewvanbreda** [comment]
Vastly improved coodinate text clarity now live, espieically on Google Hybrid (all text now white, large, with black outline)

**Comment by andrewvanbreda** [comment]
@DavidRoy 
As well as coordinate clarity improvements, I have just deployed quite a few changes to this area.
There is no longer a separate Section Details tab, so there is no need to switch between the Route and Section Details tabs, should be much simpler now.
(note length calculation not realtime yet)

**Comment by andrewvanbreda** [comment]
@DavidRoy
Real-time length tracking as you draw now live.
I will let Gary know as he wants it for EBMS.
