### ISSUE TITLE
Standardise date format

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#82]
The transect form uses: dd-mm-yyyy whereas the pan trap form uses mm-dd-yyyy
Could we standardise to dd-mmm-yyyy (i.e. month in text) to avoid mistakes?

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Hi David, I am not getting this issue.
On the Pan Trap and Transect forms it is using dd/mm/yyyy
See these screenshots after masquerading as you from the My Fixed Squares report and also the data entry page

![Screen Shot 2022-08-30 at 15 10 30](https://user-images.githubusercontent.com/2463614/187459978-2bb19762-f848-49e1-9f41-26ee2c614ed5.png)


![Screen Shot 2022-08-30 at 15 10 43](https://user-images.githubusercontent.com/2463614/187460012-ee790598-57ce-42c7-9b07-80c3790d886f.png)


Are you getting this accross different browsers and devices?

Safari and Firefox ok on my Mac, also the Transect form.

**Comment by andrewvanbreda** [comment]
Note solution to this will be same as
https://github.com/BiologicalRecordsCentre/SPRING/issues/83
I think

**Comment by DavidRoy** [comment]
Again, perhaps some help text on the page would help with this?

**Comment by andrewvanbreda** [comment]
Note added to both the Walk Data Entry, and Fixed Square Survey (pan trap) forms.
