### ISSUE TITLE
Switch to 24-hour clock

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#83]
It looked a bit confusing that you now enter the time in a 24-hrs scale but see it displayed in a 12-hrs scale with PM or AM behind it. 

Switch to 24-hour clock throughout site - only transect input page?

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy,

Again I do not seem to be getting the formatting issues you are. 
I have tried masquerading as you, using add/edit mode etc. I always seem to see 24hr format.
Are you able to send me a screenshot, and also could you send me the URL from the address bar when you are seeing the issue, that way I can double-check I am definetely looking at the same situation as you.
Thanks

**Comment by DavidRoy** [comment]
I'll ask the person who reported this.  Maybe a browser issue

**Comment by DavidRoy** [comment]
This is how it looks on Firefox for the transect input form.  The control shows hh:mm:ss whereas should be hh:mm
If time entered afternoon times as 15h, then it switches to 03h automatically.
![time](https://user-images.githubusercontent.com/2699478/187637013-8f5f6418-af12-4b6c-841f-33ea83211069.png)

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 

I am not having an issue with Firefox Mac.

However I am at John's house right now, so have checked his Windows 11 machine.
It is the operating system that decides the field format in the case of Windows. 
The HTML essentially just says the type is "time", then it is down to the user's own preferences what they see.

The way this works is actually identical to EBMS (which uses the same attribute).

If the user who is having the trouble searches for "regional format" in Windows' search, they can then adjust the "Short Time" format in the "Time & Language" settings.

We observed that adjusting this settings does affect the field format on Windows (make sure the browser is restarted after changing the setting).

Hope that helps

Andy

**Comment by DavidRoy** [comment]
Thanks @andrewvanbreda I'll pass this on

**Comment by DavidRoy** [comment]
@andrewvanbreda would it be possible to add a note to the input form about the effects of windows/browser settings on the controls?

**Comment by andrewvanbreda** [comment]
Note added to both the Walk Data Entry, and Fixed Square Survey (pan trap) forms.
