### ISSUE TITLE
Pan trap species and bycatch data entry - enable specimen code to be text

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#85]
Specimen code needs to be text: It only accepts numbers, but partner specimen codes have letters, e.g. RMNH.INS.1234567.

**Comment by andrewvanbreda** [comment]
@DavidRoy 
A fix has been deployed. 
However as it is a new attribute, it means an existing data will not be copied accross unless I hack the database.
Do you know if this field will have been used by anyone yet?

**Comment by DavidRoy** [comment]
@andrewvanbreda I don't know if there are values already in the system.  Very unlikely.  Can you check or provide me with some sql to investigate?

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
I cannot check myself.

If this returns 0 it should mean there is nothing

select sav.sample_id,sav.int_value, sav.deleted
from indicia.sample_attribute_values sav
JOIN indicia.samples s on s.id = sav.sample_id AND s.survey_id = 670 AND s.deleted=false
where sav.sample_attribute_id = 1127;

**Comment by DavidRoy** [comment]
Just one entry.  Can you move this across manually?
sample_id	sav.int_value	sav.deleted
19993923	5113736	false

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Done transfer, include a visual confirmation that value was present on the sample.

Close if happy.

**Comment by andrewvanbreda** [comment]
Closing, re-open if required.
