### ISSUE TITLE
Improve layout of pan trap species form

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/SPRING#87]
When filling species, it would help if the lines are separated by a little more color: grey line followed by a white line (this has been done in the BYCATCH entry fields and this looks much clearer).
see:
https://pollinator-monitoring.net/species-data-entry?sample_id=19993923&implicit=f
and:
https://pollinator-monitoring.net/bycatch-data-entry?sample_id=19993923&implicit=f

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy,

The apparent presentation of the bycatch form is actually an illusion.
The reason there appears to be a grey line following by a white line is that the attribute entry boxes (such as abundance) are only just a little smaller than the grid cell they are in.
This creates this illusion.

The species page is actually technically presented in the same way, however the trouble is the species name display is much longer and goes over several lines on that page.
This means the height of the of the grid rows is much higher, but the attribute entry boxes inside those cells are still the standard height, and this causes a nasty look (where a small attribute input box is appearing inside a very high cell)

I have tried to improve this situation by increasing width of species column and increasing the height of the attribute text boxes so they don't look ridiculously high, but the cell edge is also smaller.
(note if the screen is not full size, it will go back to look more like the old way as the grid runs out of room)

Old here

![Before](https://user-images.githubusercontent.com/2463614/189642410-53d7077f-fec9-4e97-9ead-a183845e3ca2.png)



New look here

![Screen Shot 2022-09-12 at 12 22 10](https://user-images.githubusercontent.com/2463614/189642441-fb272d0f-31f5-4b6a-b390-99b81bc02a9c.png)



However this is is not perfect, the trouble is that the taxon group display and the species name edit icon are taking up room.
Thing could be improved further by removing those, but then you lose functionality.

**Comment by DavidRoy** [comment]
Thanks for the explanation.  I think this one can be closed
