### ISSUE TITLE
My Transect Walks does not have walk type label (Web Review document)

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#88]
Page does not currently show a label to differentiate between butterfly and bee/hoverfly walks

**Comment by andrewvanbreda** [comment]
example
![Untitled](https://user-images.githubusercontent.com/2463614/195020240-038c4728-dd3d-4645-b963-e8170aa46aed.png)

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Could you pull this report please whenever you get a sec thanks, cheers (not urgent)
reports/projects/PoMS/poms_my_walks_list.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda This report gone live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Hi Biren, Could you pull that report again please whenever you get a second, as have made some changes.
Thanks (not urgent)

**Comment by BirenRathod** [comment]
@andrewvanbreda I have pulled it again.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Brilliant thanks :)

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Fixed and live. Walk type now appears in brackets on the grid.
