### ISSUE TITLE
Allow FIT Count Regional Coordinators to have image link in the download

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/SPRING#96]
After a discussion with James Chiazzese a slight change to the FIT Count Regional Coordinator download has been requested.
Currently the image column is useless in the download as it is just a file name. 
Append the path in the report so the image can be accessed by aware applications.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Would you be able to pull these 2 reports whenever you get a sec, thanks

reports/projects/PoMS/regional_coodinator_grid_2
reports/projects/PoMS/regional_coodinator_grid_2_download

**Comment by BirenRathod** [comment]
@andrewvanbreda Those reports gone live now.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Thanks Biren. I can see the changes :)

**Comment by andrewvanbreda** [comment]
Note to myself: Link only works when there is only 1 image.
Will discuss with James whether worth fixing.

**Comment by andrewvanbreda** [comment]
James has confirmed this is operating satisfactorily as is. 
Multi-images are in the minority and the link can easily be pasted in as needed.
