### ISSUE TITLE
Add yor results - insect species or bycatch data can be edited by any collaborator

### ISSUE THREAD

**Issue by iverkaik** [BiologicalRecordsCentre/SPRING#99]
Hello,

I just had an online session with some french volunteers and as I also experienced yesterday (with a collaborator account) any person can edit the pan-trap samples and add species or bycatch data. These results are suposed to be entered once the species have been identified by taxonomists. Not sure about who has to enter them but I suggest removing the "edit" part as it can be confussing and dangerous. 

Thank you,
Iraima

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
I am not sure what to do about this, we can't remove the edit link as that is how the screen is entered.
Did you want me to tie it down with specific roles like on UKPoMS?
It is the add species data and bycatch data which is issue here.
The original pan trap data entry can only be edited by the original person or regional coordinator, but the add species data and bycatch data area at the moment is completely open as designed.

**Comment by andrewvanbreda** [comment]
@iverkaik @DavidRoy 
Corrected, see following issue
https://github.com/BiologicalRecordsCentre/SPRING/issues/100

Note that no-one has been given the required role yet.

**Comment by DavidRoy** [comment]
Thanks.  I've assigned to all regional co-ordinators for a starter
